import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import Database from 'better-sqlite3';
import jwt from 'jsonwebtoken';

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kp-api-test-'));
const port=41000+Math.floor(Math.random()*9000),base=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,['server/index.js'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),DATA_DIR:dir,NODE_ENV:'development',API_ONLY:'1'},stdio:['ignore','pipe','pipe']});
let serverLog='';server.stdout.on('data',b=>serverLog+=b);server.stderr.on('data',b=>serverLog+=b);
async function waitForServer(){for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error('Server exited: '+serverLog);try{const r=await fetch(base+'/api/health');if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Server did not start: '+serverLog);}
async function req(url,{method='GET',body,cookie}={}){const r=await fetch(base+url,{method,headers:{'X-Requested-With':'KouturePro',...(body!==undefined?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},body:body!==undefined?JSON.stringify(body):undefined});const type=r.headers.get('content-type')||'';const json=type.includes('json')?await r.json():null;return {status:r.status,json,headers:r.headers,response:r};}
function expect(response,status){assert.equal(response.status,status,JSON.stringify(response.json));return response.json;}
const later=(days)=>new Date(Date.now()+days*864e5).toISOString().slice(0,10);

test('flux métier, isolation par atelier et balisage public',async()=>{
 await waitForServer();
 try{
  expect(await req('/api/bootstrap'),401);
  const legacyToken=jwt.sign({sub:'demo-owner'},JSON.parse(fs.readFileSync(path.join(dir,'local-secrets.json'),'utf8')).sessionKey);
  expect(await req('/api/bootstrap',{cookie:'kp_session='+legacyToken}),401);
  expect(await req('/api/auth/demo',{method:'POST'}),404);
  expect(await req('/api/auth/request-otp',{method:'POST',body:{phone:'+2250700000000'}}),404);
  expect(await req('/api/auth/verify-otp',{method:'POST',body:{phone:'+2250700000000',code:'123456'}}),404);
  expect(await req('/api/auth/login',{method:'POST',body:{identifier:'demo@kouturepro.test',password:'mauvais-mot-de-passe'}}),401);
  const login=await req('/api/auth/login',{method:'POST',body:{identifier:'DEMO@KOUTUREPRO.TEST',password:'Atelier2026!'}});expect(login,200);
  const cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/HttpOnly/);
  assert.equal(login.json.user.password_hash,undefined);assert.equal(login.json.user.email,'demo@kouturepro.test');
  const boot=expect(await req('/api/bootstrap',{cookie}),200);assert.equal(boot.organization.slug,'atelier-kone');assert.ok(boot.clients.length>=8);assert.ok(boot.measurements[0].value);assert.equal(boot.integration.mobile,false);
  assert.equal(boot.user.password_hash,undefined);assert.ok(boot.team.every(u=>u.password_hash===undefined&&u.auth_version===undefined));
  const rawDb=new Database(path.join(dir,'kouturepro.sqlite'),{readonly:true});const raw=rawDb.prepare('SELECT value_encrypted FROM measurements LIMIT 1').get();assert.ok(!/^\d+$/.test(raw.value_encrypted));
  const storedHash=rawDb.prepare("SELECT password_hash FROM users WHERE id='demo-owner'").get().password_hash;assert.match(storedHash,/^\$2[aby]\$/);assert.notEqual(storedHash,'Atelier2026!');rawDb.close();
  const c=expect(await req('/api/clients',{method:'POST',cookie,body:{id:'test-client',name:'Client Test',phone:'+2250702020202',address:'Duekoué',branch_id:'demo-branch'}}),201).item;assert.equal(c.phone,'+2250702020202');
  expect(await req('/api/clients',{method:'POST',cookie,body:{id:'test-client',name:'Client Test',branch_id:'demo-branch'}}),200);
  const m=expect(await req('/api/measurements',{method:'POST',cookie,body:{id:'test-measure',client_id:c.id,type:'Poitrine',value:'93',unit:'cm'}}),201).item;assert.equal(m.value,'93');
  expect(await req('/api/measurements/test-measure',{method:'PATCH',cookie,body:{version:99,value:'95'}}),409);
  assert.equal(expect(await req('/api/measurements/test-measure',{method:'PATCH',cookie,body:{version:m.version,value:'95'}}),200).item.value,'95');
  const audio=new FormData();audio.append('audio',new Blob([Buffer.from('note-vocale-test')],{type:'audio/webm'}),'test.webm');audio.append('client_id',c.id);
  const voiceResponse=await fetch(base+'/api/uploads/voice',{method:'POST',headers:{Cookie:cookie,'X-Requested-With':'KouturePro'},body:audio});assert.equal(voiceResponse.status,201);const voice=await voiceResponse.json();
  const played=await fetch(base+voice.url,{headers:{Cookie:cookie}});assert.equal(played.status,200);assert.equal(await played.text(),'note-vocale-test');
  const image=new FormData();image.append('image',new Blob([fs.readFileSync('public/icon-192.png')],{type:'image/png'}),'logo.png');
  const imageResponse=await fetch(base+'/api/uploads/image',{method:'POST',headers:{Cookie:cookie,'X-Requested-With':'KouturePro'},body:image});assert.equal(imageResponse.status,201);const uploaded=await imageResponse.json();
  assert.equal((await fetch(base+uploaded.url)).status,200);
  assert.equal(expect(await req('/api/organization',{method:'PATCH',cookie,body:{logo_url:uploaded.url}}),200).item.logo_url,uploaded.url);
  const fabric=boot.fabrics.find(f=>f.id==='f4');const o=expect(await req('/api/orders',{method:'POST',cookie,body:{id:'test-order',client_id:c.id,branch_id:'demo-branch',model:'Tenue de test',garment_type:'Robe',price:25000,due_date:later(5),fabric_id:'f4',fabric_quantity:2}}),201).item;assert.equal(o.price,25000);
  const boot2=expect(await req('/api/bootstrap',{cookie}),200);assert.equal(boot2.fabrics.find(f=>f.id==='f4').quantity,fabric.quantity-2);
  expect(await req('/api/orders',{method:'POST',cookie,body:{id:'test-order',client_id:c.id,branch_id:'demo-branch',model:'Tenue de test',price:25000,due_date:later(5)}}),200);
  expect(await req('/api/payments',{method:'POST',cookie,body:{id:'test-payment',order_id:o.id,amount:10000,method:'Espèces'}}),201);
  expect(await req('/api/payments',{method:'POST',cookie,body:{id:'test-overpaid',order_id:o.id,amount:30000,method:'Espèces'}}),400);
  expect(await req('/api/payments/mobile',{method:'POST',cookie,body:{order_id:o.id,amount:1000,provider:'Wave'}}),503);
  const pdf=await req('/api/orders/test-order/invoice',{cookie});assert.equal(pdf.status,200);assert.match(pdf.headers.get('content-type'),/application\/pdf/);assert.ok((await pdf.response.arrayBuffer()).byteLength>500);
  const share=expect(await req('/api/orders/test-order/invoice/share',{method:'POST',cookie}),200);assert.match(share.url,/\/receipt\//);assert.ok(Date.parse(share.expires_at)>Date.now());
  const sharedPdf=await fetch(share.url);assert.equal(sharedPdf.status,200);assert.match(sharedPdf.headers.get('content-type'),/application\/pdf/);assert.match(sharedPdf.headers.get('cache-control'),/no-store/);assert.match(sharedPdf.headers.get('x-robots-tag'),/noindex/);assert.ok((await sharedPdf.arrayBuffer()).byteLength>500);
  expect(await req('/receipt/invalid-signed-link'),404);
  expect(await req('/api/orders/test-order/invoice/whatsapp',{method:'POST',cookie}),503);
  const updated=expect(await req('/api/orders/test-order',{method:'PATCH',cookie,body:{version:o.version,stage:4}}),200).item;
  assert.equal(expect(await req('/api/orders/test-order',{method:'PATCH',cookie,body:{version:updated.version,stage:4,status:'delivered'}}),200).item.status,'delivered');
  const supplier=expect(await req('/api/suppliers',{method:'POST',cookie,body:{id:'test-supplier',name:'Fournisseur Test'}}),201).item;
  const bought=expect(await req('/api/purchases',{method:'POST',cookie,body:{id:'test-buy',fabric_id:'f4',supplier_id:supplier.id,amount:12000,quantity:4}}),201);assert.equal(bought.fabric.quantity,fabric.quantity+2);
  expect(await req('/api/public/atelier-kone/appointments',{method:'POST',body:{name:'Visiteur Test',phone:'+2250703030303',preferred_date:later(3),message:'Un RDV'}}),201);
  assert.ok(expect(await req('/api/bootstrap',{cookie}),200).appointments.some(a=>a.name==='Visiteur Test'));
  const html=await (await fetch(base+'/atelier-kone')).text();assert.match(html,/<title>Atelier Koné — Couture sur mesure/);assert.match(html,/LocalBusiness/);assert.match(html,/"@type":"Product"/);assert.match(html,/noindex/);
  const apprenticeLogin=await req('/api/auth/login',{method:'POST',body:{identifier:'+225 07 00 00 00 03',password:'Atelier2026!'}});expect(apprenticeLogin,200);
  const apprenticeCookie=apprenticeLogin.headers.get('set-cookie').split(';')[0],apprenticeData=expect(await req('/api/bootstrap',{cookie:apprenticeCookie}),200);
  assert.equal(apprenticeData.payments.length,0);assert.equal(apprenticeData.expenses.length,0);
  assert.ok(apprenticeData.orders.every(o=>o.assigned_user_id===apprenticeData.user.id&&o.price===0));
  expect(await req('/api/orders/o1',{method:'PATCH',cookie:apprenticeCookie,body:{version:1,stage:4}}),403);
  expect(await req('/api/orders/o4/invoice',{cookie:apprenticeCookie}),403);
  expect(await req('/api/orders/o4/invoice/share',{method:'POST',cookie:apprenticeCookie}),403);
  expect(await req('/api/payments',{method:'POST',cookie:apprenticeCookie,body:{order_id:'o4',amount:1000,method:'Espèces'}}),403);
  const member=expect(await req('/api/team',{method:'POST',cookie,body:{name:'Couturière de test',identifier:'couturiere@example.ci',password:'EquipeSecurisee2026!',role:'tailor',branch_id:'demo-branch'}}),201).item;
  assert.equal(member.email,'couturiere@example.ci');assert.equal(member.password_hash,undefined);
  const memberLogin=await req('/api/auth/login',{method:'POST',body:{identifier:member.email,password:'EquipeSecurisee2026!'}});expect(memberLogin,200);
  const memberCookie=memberLogin.headers.get('set-cookie').split(';')[0];assert.equal(expect(await req('/api/bootstrap',{cookie:memberCookie}),200).user.id,member.id);
  expect(await req('/api/team/'+member.id+'/password',{method:'PATCH',cookie:memberCookie,body:{password:'Interdit2026!'}}),403);
  expect(await req('/api/team/'+member.id+'/password',{method:'PATCH',cookie,body:{password:'NouveauStaff2026!'}}),200);
  expect(await req('/api/auth/me',{cookie:memberCookie}),401);
  expect(await req('/api/auth/login',{method:'POST',body:{identifier:member.email,password:'EquipeSecurisee2026!'}}),401);
  expect(await req('/api/auth/login',{method:'POST',body:{identifier:member.email,password:'NouveauStaff2026!'}}),200);
  const phone='+2250799090909',phonePassword='Motdepasse2026!';
  expect(await req('/api/auth/signup',{method:'POST',body:{name:'A',identifier:phone,password:phonePassword}}),400);
  expect(await req('/api/auth/signup',{method:'POST',body:{name:'Nouveau Patron',identifier:phone,password:'court'}}),400);
  const verify=await req('/api/auth/signup',{method:'POST',body:{name:'Nouveau Patron',identifier:phone,password:phonePassword}});assert.equal(expect(verify,201).needs_onboarding,true);
  const ownCookie=verify.headers.get('set-cookie').split(';')[0];
  expect(await req('/api/auth/signup',{method:'POST',body:{name:'Duplication',identifier:phone,password:phonePassword}}),409);
  expect(await req('/api/bootstrap',{cookie:ownCookie}),403);
  assert.equal(expect(await req('/api/auth/login',{method:'POST',body:{identifier:phone,password:phonePassword}}),200).needs_onboarding,true);
  const newOrg=expect(await req('/api/onboarding',{method:'POST',cookie:ownCookie,body:{name:'Maison Test Couture',city:'Duekoué',address:'Centre-ville',whatsapp_phone:phone,specialties:['Boubous'],plan:'starter'}}),200).organization;
  assert.equal(newOrg.slug,'maison-test-couture');assert.equal(expect(await req('/api/bootstrap',{cookie:ownCookie}),200).clients.length,0);
  const ownerRelogin=expect(await req('/api/auth/login',{method:'POST',body:{identifier:phone,password:phonePassword}}),200);
  assert.equal(ownerRelogin.needs_onboarding,false);
  assert.equal(expect(await req('/api/bootstrap',{cookie:ownCookie}),200).organization.slug,newOrg.slug);
  expect(await req('/api/clients/test-client',{method:'PATCH',cookie:ownCookie,body:{version:1,name:'Intrus'}}),404);
  expect(await req('/api/orders/test-order/invoice',{cookie:ownCookie}),404);
  expect(await req('/api/orders/test-order/invoice/share',{method:'POST',cookie:ownCookie}),404);
  const newHtml=await (await fetch(base+'/'+newOrg.slug)).text();assert.match(newHtml,/<title>Maison Test Couture/);assert.doesNotMatch(newHtml,/noindex, nofollow/);
  const sitemap=await (await fetch(base+'/sitemap.xml')).text();assert.match(sitemap,/maison-test-couture/);assert.doesNotMatch(sitemap,/atelier-kone/);
  // E-mail-only signup, normalized login, password change and session invalidation.
  const email='CLIENT@ATELIER.CI',oldPassword='Securite2026!',newPassword='NouveauMot2026!';
  const mailSignup=await req('/api/auth/signup',{method:'POST',body:{name:'Cliente Email',identifier:email,password:oldPassword}});expect(mailSignup,201);
  assert.equal(mailSignup.json.user.email,'client@atelier.ci');assert.equal(mailSignup.json.user.phone,'');
  const mailCookie=mailSignup.headers.get('set-cookie').split(';')[0];
  expect(await req('/api/auth/signup',{method:'POST',body:{name:'Duplication',identifier:'client@atelier.ci',password:oldPassword}}),409);
  expect(await req('/api/auth/change-password',{method:'POST',cookie:mailCookie,body:{current_password:'incorrect',new_password:newPassword}}),401);
  const changed=await req('/api/auth/change-password',{method:'POST',cookie:mailCookie,body:{current_password:oldPassword,new_password:newPassword}});expect(changed,200);
  expect(await req('/api/auth/me',{cookie:mailCookie}),401);
  expect(await req('/api/auth/login',{method:'POST',body:{identifier:email,password:oldPassword}}),401);
  const mailLogin=await req('/api/auth/login',{method:'POST',body:{identifier:'client@atelier.ci',password:newPassword}});expect(mailLogin,200);
  assert.equal(mailLogin.json.needs_onboarding,true);
  const emailCookie=mailLogin.headers.get('set-cookie').split(';')[0];
  assert.equal(expect(await req('/api/auth/me',{cookie:emailCookie}),200).user.password_hash,undefined);
  const mailOrg=expect(await req('/api/onboarding',{method:'POST',cookie:emailCookie,body:{name:'Atelier Mail',city:'Abidjan',whatsapp_phone:''}}),200).organization;
  assert.equal(mailOrg.whatsapp_phone,'');
  assert.equal(expect(await req('/api/bootstrap',{cookie:emailCookie}),200).organization.name,'Atelier Mail');
 }catch(error){console.error('SERVER LOG:',serverLog.slice(-3500));throw error;}finally{server.kill('SIGTERM');fs.rmSync(dir,{recursive:true,force:true});}
});
