import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

// Isolated browser journey: no changes to the live demonstration database.
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kp-auth-browser-'));
const port=48000+Math.floor(Math.random()*10000),base=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,['server/index.js'],{cwd:process.cwd(),env:{...process.env,DATA_DIR:dir,PORT:String(port),NODE_ENV:'development',SEED_DEMO:'0',SERVE_BUILD:'1'},stdio:['ignore','pipe','pipe']});
let log='';server.stdout.on('data',b=>log+=b);server.stderr.on('data',b=>log+=b);
async function wait(){for(let n=0;n<100;n++){if(server.exitCode!==null)throw Error('Serveur arrêté : '+log);try{if((await fetch(base+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Serveur non prêt : '+log);}
let browser;
try{
 await wait();browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/app',{waitUntil:'networkidle'});
 await page.getByRole('tab',{name:'Connexion'}).waitFor();
 assert.equal(new URL(page.url()).pathname,'/auth','Sans session, l’application exige une connexion.');
 assert.equal(await page.getByText('Juste une dernière étape.').count(),0);
 assert.equal(await page.getByRole('button',{name:'Recevoir mon code'}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Explorer l’atelier de démonstration'}).count(),0);
 await page.getByRole('tab',{name:'Inscription'}).click();
 await page.getByLabel(/^Votre nom/).fill('Awa Test');
 await page.getByLabel('E-mail ou numéro de téléphone').fill('AWA@EXEMPLE.CI');
 await page.getByLabel(/^Mot de passe/).fill('CoutureTest2026!');
 await page.getByLabel(/^Confirmer le mot de passe/).fill('CoutureTest2026!');
 await page.getByRole('button',{name:'Créer mon compte'}).click();
 await page.getByRole('heading',{name:'Comment s’appelle votre atelier ?'}).waitFor();
 assert.equal(await page.getByText('Étape 2 sur 5').isVisible(),true,'L’inscription doit poursuivre ses étapes.');
 await page.getByLabel('Nom de votre atelier').fill('Maison des Étoiles');
 await page.getByRole('button',{name:/Continuer/}).click();
 await page.getByRole('heading',{name:'Où vous trouve-t-on ?'}).waitFor();
 await page.getByLabel('Ville').fill('Duekoué');
 await page.getByLabel('WhatsApp professionnel').fill('+2250701012345');
 await page.getByRole('button',{name:/Continuer/}).click();
 await page.getByRole('heading',{name:'Que créez-vous ?'}).waitFor();
 await page.getByRole('button',{name:/Boubous & ensembles/}).click();
 await page.getByRole('button',{name:/Continuer/}).click();
 await page.getByRole('heading',{name:'Un plan pour commencer.'}).waitFor();
 await page.getByRole('button',{name:'Ouvrir mon tableau de bord'}).click();
 await page.getByRole('heading',{name:/Bonjour Awa/}).waitFor();
 assert.equal(new URL(page.url()).pathname,'/app');
 const ownDashboard=await page.request.get(base+'/api/bootstrap');assert.equal(ownDashboard.status(),200);
 assert.equal((await ownDashboard.json()).organization.slug,'maison-des-etoiles','Chaque compte doit ouvrir son propre atelier.');
 const publicSite=await page.request.get(base+'/maison-des-etoiles');assert.equal(publicSite.status(),200);
 await page.goto(base+'/app/settings');await page.getByRole('heading',{name:'Paramètres'}).waitFor();
 await page.locator('.logout-btn').click();await page.getByRole('tab',{name:'Connexion'}).waitFor();
 await page.goto(base+'/app');await page.getByRole('tab',{name:'Connexion'}).waitFor();
 await page.getByLabel('E-mail ou numéro de téléphone').fill('awa@exemple.ci');
 await page.getByLabel(/^Mot de passe/).fill('CoutureTest2026!');
 await page.getByRole('button',{name:'Se connecter'}).click();
 await page.getByRole('heading',{name:/Bonjour Awa/}).waitFor();
 // A connected account can continue reading its own cached data without network.
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await page.context().setOffline(true);await page.reload({waitUntil:'domcontentloaded'});
 await page.getByRole('heading',{name:/Bonjour Awa/}).waitFor();
 await page.context().setOffline(false);await page.reload({waitUntil:'networkidle'});
 await page.goto(base+'/app/settings');await page.getByRole('heading',{name:'Paramètres'}).waitFor();
 await page.locator('.settings-card').filter({hasText:'Sécurité du compte'}).getByRole('button',{name:/Modifier/}).click();
 await page.getByLabel(/^Mot de passe actuel/).fill('CoutureTest2026!');
 await page.getByLabel(/^Nouveau mot de passe/).fill('NouveauCouture2026!');
 await page.getByLabel(/^Confirmer le nouveau mot de passe/).fill('NouveauCouture2026!');
 await page.getByRole('button',{name:'Enregistrer le mot de passe'}).click();
 await page.getByRole('dialog',{name:'Changer mon mot de passe'}).waitFor({state:'hidden'});
 await page.locator('.logout-btn').click();await page.getByRole('tab',{name:'Connexion'}).waitFor();
 await page.getByLabel('E-mail ou numéro de téléphone').fill('awa@exemple.ci');
 await page.getByLabel(/^Mot de passe/).fill('NouveauCouture2026!');
 await page.getByRole('button',{name:'Se connecter'}).click();await page.getByRole('heading',{name:/Bonjour Awa/}).waitFor();
 const context=await browser.newContext({viewport:{width:390,height:844}});const phone=await context.newPage();phone.on('pageerror',e=>errors.push(e.message));
 await phone.goto(base+'/auth');await phone.getByRole('tab',{name:'Inscription'}).click();
 await phone.getByLabel(/^Votre nom/).fill('Fatou Téléphone');
 await phone.getByLabel('E-mail ou numéro de téléphone').fill('+225 07 09 09 01 01');
 await phone.getByLabel(/^Mot de passe/).fill('CouturePhone2026!');
 await phone.getByLabel(/^Confirmer le mot de passe/).fill('CouturePhone2026!');
 await phone.getByRole('button',{name:'Créer mon compte'}).click();
 await phone.getByRole('heading',{name:'Comment s’appelle votre atelier ?'}).waitFor();
 const me=await phone.request.get(base+'/api/auth/me');assert.equal(me.status(),200);const user=(await me.json()).user;
 assert.equal(user.phone,'+2250709090101');assert.equal(user.email,'');assert.equal(user.password_hash,undefined);
 assert.deepEqual(errors,[]);
 console.log('✓ Sans session : Connexion / Inscription, aucun code ni démo automatique');
 console.log('✓ Inscription e-mail → onboarding → atelier → déconnexion → connexion');
 console.log('✓ Rechargement hors ligne et changement de mot de passe dans Paramètres');
 console.log('✓ Inscription téléphone sans code, identifiant normalisé');
}finally{if(browser)await browser.close();server.kill('SIGTERM');fs.rmSync(dir,{recursive:true,force:true});}
