import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('tmp',{recursive:true});
const base=process.env.KP_BASE_URL||'http://localhost:3000';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const step=async(name,fn)=>{try{await fn();console.log('✓',name)}catch(e){console.error('✗',name,e.message);await page.screenshot({path:'tmp/e2e-error.png',fullPage:true});throw e;}};
try{
 await step('Connexion requise, puis tableau de bord démo',async()=>{await page.goto(base+'/app');await page.getByRole('tab',{name:'Connexion'}).waitFor();await page.getByLabel('E-mail ou numéro de téléphone').fill('demo@kouturepro.test');await page.getByLabel(/^Mot de passe/).fill(process.env.DEMO_PASSWORD||'Atelier2026!');await page.getByRole('button',{name:'Se connecter'}).click();await page.getByRole('heading',{name:/Bonjour Awa/}).waitFor();});
 await step('Créer un client',async()=>{await page.locator('.sidebar .nav-item').filter({hasText:'Clients'}).click();await page.getByRole('button',{name:'Nouveau client'}).click();await page.getByLabel('Nom complet').fill('Élodie QA');await page.getByLabel('Téléphone').fill('+2250798888822');await page.getByRole('button',{name:'Ajouter le client'}).click();await page.getByRole('heading',{name:'Élodie QA'}).waitFor();});
 await step('Ajouter et modifier une mesure',async()=>{await page.getByRole('button',{name:'Ajouter une mesure'}).click();await page.getByLabel('Valeur').fill('95');await page.getByRole('button',{name:'Enregistrer la mesure'}).click();await page.getByText('95',{exact:false}).first().waitFor();await page.getByRole('button',{name:'Modifier Poitrine'}).click();await page.getByLabel('Valeur').fill('96');await page.getByRole('button',{name:'Mettre à jour la mesure'}).click();await page.locator('.measure-item').filter({hasText:'Poitrine'}).getByText('96').waitFor();});
 await step('Créer commande + acompte',async()=>{await page.locator('.sidebar .nav-item').filter({hasText:'Commandes'}).click();await page.getByRole('button',{name:'Nouvelle commande'}).click();await page.locator('select[name="client_id"]').selectOption(await page.locator('select[name="client_id"] option').filter({hasText:'Élodie QA'}).first().getAttribute('value'));await page.getByLabel('Modèle / description').fill('Robe test QA');await page.getByRole('button',{name:/Continuer/}).click();await page.getByLabel('Prix total (FCFA)').fill('24000');await page.getByLabel('Acompte reçu en espèces').fill('5000');const tomorrow=new Date(Date.now()+3*864e5).toISOString().slice(0,10);await page.getByLabel('Date de livraison').fill(tomorrow);await page.getByRole('button',{name:'Créer la commande'}).click();await page.getByRole('heading',{name:'Robe test QA'}).waitFor();assert.ok(await page.getByText('5 000 FCFA',{exact:false}).count()>0);});
 await step('Faire progresser la commande',async()=>{await page.getByRole('button',{name:'Passer à l’étape suivante'}).click();await page.getByText('Étape actuelle : Découpe').waitFor();});
 await step('Encaisser et facture PDF',async()=>{await page.getByRole('button',{name:'Encaisser un paiement'}).click();await page.getByLabel('Montant à encaisser (FCFA)').fill('19000');await page.getByRole('button',{name:'Confirmer le paiement'}).click();await page.getByText('0 FCFA',{exact:false}).first().waitFor();const href=await page.getByRole('link',{name:'Facture PDF',exact:true}).getAttribute('href');const pdf=await page.request.get(base+href);assert.equal(pdf.status(),200);assert.match(pdf.headers()['content-type'],/application\/pdf/);});
 await step('Mode hors ligne puis synchro',async()=>{await page.locator('.sidebar .nav-item').filter({hasText:'Paramètres'}).click();await page.getByRole('switch',{name:'Simuler hors ligne'}).click();await page.getByText('Vous travaillez hors ligne').waitFor();await page.locator('.sidebar .nav-item').filter({hasText:'Clients'}).click();await page.getByRole('button',{name:'Nouveau client'}).click();await page.getByLabel('Nom complet').fill('Test hors ligne');await page.getByRole('button',{name:'Ajouter le client'}).click();await page.getByRole('heading',{name:'Test hors ligne'}).waitFor();await page.locator('.sidebar .nav-item').filter({hasText:'Paramètres'}).click();await page.getByRole('switch',{name:'Simuler hors ligne'}).click();await page.waitForTimeout(1500);await page.getByText('Tout est synchronisé').waitFor();});
 await step('Vitrine publique + rendez-vous',async()=>{await page.goto(base+'/atelier-kone');await page.getByRole('heading',{name:/L’élégance/}).waitFor();await page.getByRole('button',{name:'Prendre rendez-vous'}).first().click();await page.getByLabel('Votre nom').fill('Client Public QA');await page.getByLabel('Votre téléphone').fill('+2250712121212');await page.getByLabel('Date souhaitée').fill(new Date(Date.now()+4*864e5).toISOString().slice(0,10));await page.getByRole('button',{name:/Envoyer ma demande/}).click();await page.getByRole('heading',{name:'Merci pour votre confiance.'}).waitFor();});
 await step('Navigation écrans mobiles',async()=>{await page.setViewportSize({width:390,height:844});await page.goto(base+'/app');await page.getByRole('heading',{name:/Bonjour Awa/}).waitFor();await page.locator('.bottom-nav').getByRole('button',{name:'Plus'}).click();await page.getByRole('button',{name:'Stock & fournisseurs'}).click();await page.getByRole('heading',{name:'Stock & fournisseurs'}).waitFor();await page.screenshot({path:'tmp/stock-mobile.png',fullPage:false});});
 console.log('JS ERRORS',errors);assert.deepEqual(errors,[]);
}finally{await browser.close();}
