import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Plus, Search, ChevronRight, ArrowLeft, Phone, MessageCircle, Ruler, ShoppingBag, MapPin, Mic, Square, Play, Trash2, Pencil, CalendarDays, CircleHelp, Sparkles, ClipboardList, FileText, UserRound, ArrowUpRight, Layers3} from 'lucide-react';
import {useApp} from '../App.jsx';
import {PageHeader,Card,PanelHead,Button,Badge,Avatar,SearchInput,Tabs,Modal,Input,Select,Field,FormActions,Empty,IconButton} from '../components.jsx';
import {money,dateFR,orderBalance,waLink,uuid,stages,fmt} from '../utils.js';

const TYPES=['Poitrine','Taille','Hanches','Épaules','Longueur robe','Longueur manche','Tour de bras','Tour de cou','Entrejambe','Longueur pantalon','Tour de poignet','Autre'];
export default function Clients(){
 const {data,branch,navigate,route,mutate,notify}=useApp();const query=new URLSearchParams(route.split('?')[1]||'');const chosen=query.get('client'),newClient=query.get('new')==='1';
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all');
 const clients=data.clients.filter(c=>branch==='all'||c.branch_id===branch).filter(c=>c.name.toLowerCase().includes(search.toLowerCase())||c.phone.includes(search));
 const list=clients.filter(c=>filter==='all'||filter==='active'&&data.orders.some(o=>o.client_id===c.id&&o.status==='active')||filter==='recent'&&new Date(c.created_at).getTime()>Date.now()-30*864e5);
 const client=data.clients.find(c=>c.id===chosen);
 if(client)return <ClientDetail client={client} onBack={()=>navigate('/app/clients')}/>;
 return <><PageHeader eyebrow="VOTRE CARNET D’ADRESSES" title="Clients" subtitle={`${data.clients.length} client${data.clients.length>1?'s':''} dans votre atelier. Chaque détail, au bon endroit.`} action={data.user.role!=='apprentice'&&<Button icon={Plus} onClick={()=>navigate('/app/clients?new=1')}>Nouveau client</Button>}/>
 <Card className="list-page-card"><div className="list-toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Rechercher par nom ou téléphone"/><div className="segmented">{[['all','Tous'],['active','Actifs'],['recent','Récents']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div></div>
 <div className="client-table-head"><span>CLIENT</span><span>CONTACT</span><span>COMMANDES</span><span>À ENCAISSER</span><span></span></div>
 <div className="client-list">{list.map((c,i)=>{const os=data.orders.filter(o=>o.client_id===c.id);const due=os.reduce((a,o)=>a+orderBalance(o,data.payments),0);return <button key={c.id} className="client-row" onClick={()=>navigate('/app/clients?client='+c.id)}><span className="client-cell-name"><Avatar name={c.name} color={data.clients.indexOf(c)} /><span><strong>{c.name}</strong><small>Client depuis {dateFR(c.created_at,{month:'long',year:'numeric'})}</small></span></span><span className="client-phone">{c.phone||'—'}</span><span className="client-orders">{os.length} commande{os.length>1?'s':''}</span><span className="client-balance">{data.user.role==='apprentice'?<span className="paid-label">{os.filter(o=>o.status==='active').length} en cours</span>:due>0?money(due):<span className="paid-label">À jour</span>}</span><ChevronRight size={18} className="muted-chevron"/></button>})}</div>
 {!list.length&&<Empty icon={UserRound} title="Aucun client trouvé" description={search?'Essayez un autre nom ou numéro.':'Ajoutez votre premier client pour commencer.'} action={!search&&data.user.role!=='apprentice'&&<Button icon={Plus} onClick={()=>navigate('/app/clients?new=1')}>Ajouter un client</Button>}/>}</Card>
 {newClient&&data.user.role!=='apprentice'&&<ClientForm onClose={()=>navigate('/app/clients')}/>}
 </>;
}
function ClientForm({onClose,client}){const {mutate,branch,data,notify,navigate}=useApp();const [form,setForm]=useState({name:client?.name||'',phone:client?.phone||'',address:client?.address||'',notes:client?.notes||''}),[busy,setBusy]=useState(false);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);const id=client?.id||uuid(),body={...form,...(client?{version:client.version}:{id,branch_id:branch==='all'?data.branches[0]?.id:branch})};
 try{await mutate(client?'PATCH':'POST',client?'/api/clients/'+client.id:'/api/clients',body,old=>({...old,clients:client?old.clients.map(c=>c.id===id?{...c,...form,version:c.version+1}:c):[{...body,created_at:new Date().toISOString(),version:1},...old.clients]}));notify(client?'Fiche client mise à jour.':'Client ajouté avec succès.');onClose();if(!client)navigate('/app/clients?client='+id);}catch(err){notify(err.message,'error');}finally{setBusy(false);}};
 return <Modal title={client?'Modifier le client':'Nouveau client'} subtitle={client?'Gardez les informations de votre client à jour.':'Une fiche simple à remplir, même entre deux essayages.'} onClose={onClose}><form onSubmit={submit} className="form-stack"><Input label="Nom complet" name="name" placeholder="Ex. Aminata Traoré" value={form.name} onChange={change} required autoFocus/><Input label="Téléphone" name="phone" type="tel" inputMode="tel" placeholder="+225 07 00 00 00 00" value={form.phone} onChange={change} hint="Utile pour envoyer vos rappels et messages WhatsApp."/><Input label="Quartier ou adresse" name="address" placeholder="Ex. Cocody, Abidjan" value={form.address} onChange={change}/><Input label="Notes utiles" name="notes" placeholder="Préférences, habitudes..." value={form.notes} onChange={change} as="textarea" rows={3}/><FormActions onCancel={onClose} loading={busy} label={client?'Enregistrer les changements':'Ajouter le client'}/></form></Modal>;
}
function ClientDetail({client,onBack}){const {data,navigate,mutate,notify,online}=useApp(),[tab,setTab]=useState('mesures'),[edit,setEdit]=useState(false),[addMeasure,setAddMeasure]=useState(false),[editingMeasure,setEditingMeasure]=useState(null);const measures=data.measurements.filter(m=>m.client_id===client.id),orders=data.orders.filter(o=>o.client_id===client.id).sort((a,b)=>b.created_at.localeCompare(a.created_at)),balance=orders.reduce((sum,o)=>sum+orderBalance(o,data.payments),0);
 const comparisons=useMemo(()=>{if(measures.length<3)return [];const current=Object.fromEntries(measures.map(m=>[m.type,Number(m.value)]));return data.clients.filter(c=>c.id!==client.id).map(c=>{let matches=0,compared=0;for(const m of data.measurements.filter(x=>x.client_id===c.id)){if(Number.isFinite(current[m.type])&&Number.isFinite(Number(m.value))){compared++;if(Math.abs(current[m.type]-Number(m.value))<=3)matches++;}}return {client:c,score:compared?matches/compared:0,compared};}).filter(x=>x.compared>=3&&x.score>=.65).sort((a,b)=>b.score-a.score).slice(0,2)},[client.id,data.measurements,data.clients]);
 return <><button className="back-link" onClick={onBack}><ArrowLeft size={17}/> Retour aux clients</button><div className="client-detail-head"><div className="client-detail-main"><Avatar name={client.name} size="xl" color={data.clients.indexOf(client)}/><div><div className="eyebrow">FICHE CLIENT</div><h1>{client.name}</h1><span>{client.phone||'Pas de numéro'} <i>·</i> {client.address||'Adresse non renseignée'}</span></div></div><div className="detail-actions">{data.user.role!=='apprentice'&&<Button variant="soft" icon={Pencil} onClick={()=>setEdit(true)}>Modifier</Button>}{client.phone&&<a className="btn btn-primary" target="_blank" rel="noopener noreferrer" href={waLink(client.phone,`Bonjour ${client.name}, c'est ${data.organization.name}.`)}><MessageCircle size={17}/><span>WhatsApp</span></a>}</div></div>
 <div className="client-info-stats"><div><span>COMMANDES</span><strong>{orders.length}</strong></div><div><span>MESURES</span><strong>{measures.length}</strong></div><div><span>{data.user.role==='apprentice'?'EN COURS':'RESTE À PAYER'}</span><strong>{data.user.role==='apprentice'?orders.filter(o=>o.status==='active').length:money(balance)}</strong></div></div>
 <Tabs active={tab} onChange={setTab} items={[{key:'mesures',label:'Mesures',count:measures.length},{key:'commandes',label:'Commandes',count:orders.length},{key:'infos',label:'Informations'}]}/>
 {tab==='mesures'&&<div className="detail-columns"><Card><PanelHead title="Carnet de mesures" subtitle="Mesures conservées en toute sécurité" icon={Ruler} action={<Button size="sm" icon={Plus} onClick={()=>setAddMeasure(true)}>Ajouter une mesure</Button>}/>{measures.length?<div className="measure-grid">{measures.map(m=><div key={m.id} className="measure-item"><span>{m.type}</span><strong>{m.value} <small>{m.unit}</small></strong><div>{m.voice_id&&(!m.voice_id.startsWith('local-')?<audio src={'/api/uploads/voice/'+m.voice_id} controls preload="none" aria-label={'Note vocale '+m.type}/>:<small className="waiting-sync">🎙 Note en attente de synchro</small>)}<button title="Modifier cette mesure" aria-label={'Modifier '+m.type} onClick={()=>setEditingMeasure(m)}><Pencil size={15}/></button>{data.user.role!=='apprentice'&&<button title="Supprimer cette mesure" aria-label={'Supprimer '+m.type} onClick={async()=>{if(!confirm('Supprimer cette mesure ?'))return;try{await mutate('DELETE','/api/measurements/'+m.id,undefined,old=>({...old,measurements:old.measurements.filter(x=>x.id!==m.id)}));notify('Mesure supprimée.');}catch(e){notify(e.message,'error');}}}><Trash2 size={15}/></button>}</div></div>)}</div>:<Empty icon={Ruler} title="Un carnet à remplir" description="Ajoutez ses premières mesures pour ne plus chercher dans un cahier. Utilisez « Ajouter une mesure » ci-dessus."/>}</Card>
 <div className="detail-side-stack"><Card className="insight-card"><div className="insight-icon"><Sparkles size={20}/></div><h3>Des mesures qui se ressemblent</h3>{comparisons.length?<><p>Ces clients ont des mensurations proches. Un patron existant pourrait vous faire gagner du temps.</p>{comparisons.map(x=><button key={x.client.id} onClick={()=>navigate('/app/clients?client='+x.client.id)}><Avatar name={x.client.name} size="xs"/><span>{x.client.name}</span><Badge tone="mint">{Math.round(x.score*100)}% proches</Badge></button>)}</>:<p>Ajoutez au moins 3 mesures pour voir les profils similaires et réutiliser vos patrons.</p>}</Card><Card className="small-info-card"><div className="icon-square"><ClipboardList size={18}/></div><div><h3>Patrons réutilisables</h3><p>{data.patterns.length} modèle{data.patterns.length>1?'s':''} à disposition pour une prochaine commande.</p><button onClick={()=>navigate('/app/production')}>Voir la bibliothèque <ChevronRight size={15}/></button></div></Card></div></div>}
 {tab==='commandes'&&<Card className="client-orders-card"><PanelHead title="Historique des commandes" subtitle="Toutes ses créations au même endroit" icon={ShoppingBag} action={['owner','tailor'].includes(data.user.role)&&<Button size="sm" icon={Plus} onClick={()=>navigate('/app/orders?new=1&client='+client.id)}>Nouvelle commande</Button>}/>{orders.length?orders.map(o=><button className="detail-order-row" key={o.id} onClick={()=>navigate('/app/orders/'+o.id)}><span className="detail-order-symbol"><ShoppingBag size={19}/></span><span><strong>{o.model}</strong><small>{o.reference} · Livraison {dateFR(o.due_date)}</small></span>{data.user.role!=='apprentice'&&<strong>{money(o.price)}</strong>}<ChevronRight size={17}/></button>):<Empty icon={ShoppingBag} title="Pas encore de commande" description="La prochaine création pour ce client apparaîtra ici."/>}</Card>}
 {tab==='infos'&&<Card className="infos-card"><PanelHead title="Coordonnées & notes" action={data.user.role!=='apprentice'&&<Button variant="soft" size="sm" icon={Pencil} onClick={()=>setEdit(true)}>Modifier</Button>}/><div className="infos-row"><Phone size={19}/><div><small>Téléphone</small><strong>{client.phone||'Non renseigné'}</strong></div></div><div className="infos-row"><MapPin size={19}/><div><small>Adresse</small><strong>{client.address||'Non renseignée'}</strong></div></div><div className="infos-row"><FileText size={19}/><div><small>Notes</small><strong>{client.notes||'Aucune note pour le moment.'}</strong></div></div><div className="infos-row"><CalendarDays size={19}/><div><small>Client depuis</small><strong>{dateFR(client.created_at)}</strong></div></div></Card>}
 {edit&&<ClientForm client={client} onClose={()=>setEdit(false)}/>} {addMeasure&&<MeasureForm client={client} onClose={()=>setAddMeasure(false)}/>} {editingMeasure&&<MeasureForm client={client} measurement={editingMeasure} onClose={()=>setEditingMeasure(null)}/>}</>;
}
function MeasureForm({client,onClose,measurement}){const {mutate,notify}=useApp();const [form,setForm]=useState({type:measurement?(TYPES.includes(measurement.type)?measurement.type:'Autre'):'Poitrine',value:measurement?.value||'',unit:measurement?.unit||'cm'}),[custom,setCustom]=useState(measurement&&!TYPES.includes(measurement.type)?measurement.type:''),[recording,setRecording]=useState(false),[blob,setBlob]=useState(null),[busy,setBusy]=useState(false),recRef=useRef(null),streamRef=useRef(null);
 const start=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const type=MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':MediaRecorder.isTypeSupported('audio/mp4')?'audio/mp4':'';const rec=new MediaRecorder(stream,type?{mimeType:type}:undefined),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{setBlob(new Blob(chunks,{type:rec.mimeType||'audio/webm'}));stream.getTracks().forEach(t=>t.stop());};rec.start();recRef.current=rec;setRecording(true);}catch(e){notify("Impossible d'accéder au micro. Autorisez-le dans le navigateur.",'error');}};
 const stop=()=>{recRef.current?.stop();setRecording(false)};useEffect(()=>()=>{if(recRef.current?.state==='recording')recRef.current.stop();streamRef.current?.getTracks().forEach(t=>t.stop())},[]);
 const submit=async e=>{e.preventDefault();setBusy(true);const type=form.type==='Autre'?custom.trim():form.type;if(!type){notify('Précisez le nom de la mesure.','error');setBusy(false);return;}const id=measurement?.id||uuid(),body={id,client_id:client.id,type,value:String(form.value).trim(),unit:form.unit,...(measurement?{version:measurement.version}:{}),...(blob?{audio:blob}:{})};
 try{await mutate(blob?'VOICE_MEASURE':measurement?'PATCH':'POST',measurement?'/api/measurements/'+id:'/api/measurements',body,old=>({...old,measurements:measurement?old.measurements.map(m=>m.id===id?{...m,type,value:body.value,unit:body.unit,version:m.version+1,voice_id:blob?'local-'+id:m.voice_id}:m):[{id,client_id:client.id,type,value:body.value,unit:body.unit,version:1,voice_id:blob?'local-'+id:'',created_at:new Date().toISOString()},...old.measurements]}));notify(measurement?'Mesure mise à jour.':'Mesure enregistrée.');onClose();}catch(e){notify(e.message,'error')}finally{setBusy(false)};
 };
 return <Modal title={measurement?'Modifier la mesure':'Ajouter une mesure'} subtitle={`Carnet de ${client.name}`} onClose={onClose}><form className="form-stack" onSubmit={submit}><Select label="Mesure" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</Select>{form.type==='Autre'&&<Input label="Nom de la mesure" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Ex. Tour de genou" required/>}<div className="form-two"><Input label="Valeur" type="number" step="0.1" min="0" inputMode="decimal" placeholder="Ex. 92" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} required/><Select label="Unité" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option>cm</option><option>mm</option><option>pouces</option></Select></div><div className="voice-field"><div><Mic size={18}/><span><strong>Note vocale</strong><small>Un détail à retenir ? Dites-le à voix haute.</small></span></div>{blob?<span className="voice-saved"><Play size={14}/> Audio prêt <button type="button" onClick={()=>setBlob(null)}>Retirer</button></span>:<button type="button" className={'voice-record '+(recording?'recording':'')} onClick={recording?stop:start}>{recording?<><Square size={14}/> Arrêter</>:<><Mic size={15}/> Enregistrer</>}</button>}</div><FormActions onCancel={onClose} loading={busy} label={measurement?'Mettre à jour la mesure':'Enregistrer la mesure'}/></form></Modal>;
}
