import React from 'react';
import {ArrowUpRight, ArrowRight, CalendarDays, Clock3, CircleAlert, CheckCircle2, ShoppingBag, Wallet, TrendingUp, PackageCheck, ChevronRight, Plus, Sparkles, Boxes, CalendarCheck, Eye, Scissors} from 'lucide-react';
import {useApp} from '../App.jsx';
import {PageHeader,Card,PanelHead,Button,Badge,Avatar,SectionLink,StatCard,Empty} from '../components.jsx';
import {money,shortMoney,fmt,stages,stageColors,dateFR,orderBalance,orderState,stateTone,today,orgPublicPath} from '../utils.js';

export default function Dashboard(){
 const {data,navigate,setQuick,branch}=useApp(),me=data.user.name.split(' ')[0],thisMonth=today().slice(0,7),prevDate=new Date();prevDate.setUTCMonth(prevDate.getUTCMonth()-1);const prevMonth=prevDate.toISOString().slice(0,7);
 const orders=data.orders.filter(o=>branch==='all'||o.branch_id===branch),orderIds=new Set(orders.map(o=>o.id)),payments=data.payments.filter(p=>orderIds.has(p.order_id)&&p.status==='paid');
 const revenue=payments.filter(p=>p.created_at.slice(0,7)===thisMonth).reduce((a,p)=>a+p.amount,0),prevRevenue=payments.filter(p=>p.created_at.slice(0,7)===prevMonth).reduce((a,p)=>a+p.amount,0);
 const change=prevRevenue?Math.round((revenue/prevRevenue-1)*100):0;
 const active=orders.filter(o=>o.status==='active'),unpaid=orders.filter(o=>o.status!=='cancelled').reduce((sum,o)=>sum+orderBalance(o,payments),0),unpaidOrders=orders.filter(o=>o.status!=='cancelled'&&orderBalance(o,payments)>0).length;
 const delivered=orders.filter(o=>o.status==='delivered'&&o.delivered_at.slice(0,7)===thisMonth).length;
 const urgencies=active.filter(o=>o.due_date<=today()||o.fitting_date===today()).sort((a,b)=>a.due_date.localeCompare(b.due_date));
 const recent=[...orders].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,5);
 const lowFabrics=data.fabrics.filter(f=>(branch==='all'||f.branch_id===branch)&&f.quantity<=f.threshold);
 const appointments=data.appointments.filter(a=>a.status==='new');
 if(data.user.role==='apprentice')return <><PageHeader eyebrow="MON ESPACE DE TRAVAIL" title={<>Bonjour {me} <span className="wave-emoji">👋</span></>} subtitle="Retrouvez vos créations et faites-les avancer." action={<Button icon={Scissors} onClick={()=>navigate('/app/production')}>Voir mes tâches</Button>}/><div className="welcome-strip"><span className="welcome-strip-icon"><Sparkles size={18}/></span><p><strong>À vos ciseaux !</strong> {active.length} création{active.length>1?'s':''} vous {active.length>1?'attendent':'attend'} aujourd’hui.</p></div><Card className="priority-card"><PanelHead title="Mes commandes à suivre" subtitle="Les créations qui vous sont confiées" icon={Scissors} action={<Badge tone="mint">{active.length} en cours</Badge>}/><div className="priority-list">{active.map(o=><button className="priority-row" key={o.id} onClick={()=>navigate('/app/orders/'+o.id)}><span className="priority-symbol priority-blue"><Scissors size={19}/></span><span className="priority-info"><strong>{o.model}</strong><small>{data.clients.find(c=>c.id===o.client_id)?.name} · Étape : {stages[o.stage]}</small></span><span className="priority-date"><Badge tone={stateTone(orderState(o))}>{orderState(o)}</Badge><small>{dateFR(o.due_date)}</small></span><ChevronRight size={18} className="muted-chevron"/></button>)}{!active.length&&<div className="priority-clear"><CheckCircle2 size={24}/><div><strong>Tout est à jour</strong><p>Aucune nouvelle tâche ne vous est confiée pour le moment.</p></div></div>}</div></Card></>;
 return <>
  <PageHeader eyebrow="VUE D’ENSEMBLE" title={<>Bonjour {me} <span className="wave-emoji">👋</span></>} subtitle="Voici ce qui se passe dans votre atelier aujourd’hui." action={<Button icon={Plus} onClick={()=>setQuick(true)}>Nouvelle commande</Button>} extra={<a className="btn btn-soft view-site" href={orgPublicPath(data)} target="_blank" rel="noreferrer"><Eye size={17}/><span>Voir ma vitrine</span></a>}/>
  <div className="welcome-strip"><span className="welcome-strip-icon"><Sparkles size={18}/></span><p><strong>Une belle journée pour créer !</strong> Vous avez <b>{active.length} commandes en cours</b>{urgencies.length>0?` et ${urgencies.length} priorité${urgencies.length>1?'s':''} à traiter`:' et aucune urgence en attente'}.</p><button onClick={()=>navigate('/app/production')}>Voir la production <ArrowRight size={15}/></button></div>
  <div className="stats-grid">
   <StatCard label="Chiffre d'affaires ce mois" value={money(revenue)} sub="encaissé ce mois-ci" icon={Wallet} tone="green" trend={prevRevenue?`${change>=0?'+':''}${change}% vs mois dernier`:undefined} onClick={()=>navigate('/app/payments')}/>
   <StatCard label="Reste à encaisser" value={money(unpaid)} sub={`${unpaidOrders} commande${unpaidOrders>1?'s':''} à solder`} icon={CircleAlert} tone="amber" onClick={()=>navigate('/app/payments')}/>
   <StatCard label="Commandes en cours" value={fmt(active.length)} sub="dans votre atelier" icon={ShoppingBag} tone="blue" onClick={()=>navigate('/app/orders')}/>
   <StatCard label="Livrées ce mois" value={fmt(delivered)} sub="créations terminées" icon={PackageCheck} tone="purple" onClick={()=>navigate('/app/orders?status=delivered')}/>
  </div>
  <div className="dashboard-layout"><div className="dash-primary">
   <Card className="priority-card"><PanelHead title="Priorités du jour" subtitle="Les commandes qui demandent votre attention" icon={CircleAlert} action={<Badge tone={urgencies.length?'red':'green'}>{urgencies.length} à suivre</Badge>}/>
    <div className="priority-list">{urgencies.slice(0,4).map((o,i)=>{const c=data.clients.find(x=>x.id===o.client_id),late=o.due_date<today(),fitting=o.fitting_date===today()&&!late;return <button className="priority-row" key={o.id} onClick={()=>navigate('/app/orders/'+o.id)}><span className={'priority-symbol '+(late?'priority-red':fitting?'priority-blue':'priority-amber')}>{late?<CircleAlert size={19}/>:fitting?<Scissors size={19}/>:<Clock3 size={19}/>}</span><span className="priority-info"><strong>{o.model}</strong><small>{c?.name} <span>·</span> {o.reference}</small></span><span className="priority-date"><Badge tone={late?'red':fitting?'blue':'amber'}>{late?'En retard':fitting?'Essayage':'À livrer'}</Badge><small>{dateFR(fitting?o.fitting_date:o.due_date,{day:'numeric',month:'short'})}</small></span><ChevronRight size={18} className="muted-chevron"/></button>})}{!urgencies.length&&<div className="priority-clear"><CheckCircle2 size={24}/><div><strong>Tout est sous contrôle</strong><p>Vous n’avez aucune urgence aujourd’hui.</p></div></div>}</div>
    <div className="card-bottom-link"><SectionLink onClick={()=>navigate('/app/orders?status=urgent')}>Voir toutes les commandes</SectionLink></div>
   </Card>
   <Card className="recent-card"><PanelHead title="Commandes récentes" subtitle="Suivez les derniers travaux de votre atelier" icon={ShoppingBag} action={<SectionLink onClick={()=>navigate('/app/orders')}>Toutes les commandes</SectionLink>}/>
    <div className="table-wrap"><table className="data-table"><thead><tr><th>COMMANDE</th><th>CLIENT</th><th>LIVRAISON</th><th>MONTANT</th><th>STATUT</th><th></th></tr></thead><tbody>{recent.map(o=>{const c=data.clients.find(x=>x.id===o.client_id);return <tr key={o.id} onClick={()=>navigate('/app/orders/'+o.id)}><td><strong>{o.model}</strong><small>{o.reference}</small></td><td><div className="table-person"><Avatar name={c?.name} size="xs" color={data.clients.indexOf(c)}/><span>{c?.name||'—'}</span></div></td><td>{dateFR(o.due_date,{day:'numeric',month:'short',year:'numeric'})}</td><td className="table-amount">{money(o.price)}</td><td><Badge tone={stateTone(orderState(o))} dot>{orderState(o)}</Badge></td><td><ChevronRight size={17}/></td></tr>})}</tbody></table></div>
    <div className="mobile-order-list">{recent.map(o=>{const c=data.clients.find(x=>x.id===o.client_id);return <button key={o.id} className="mobile-order-item" onClick={()=>navigate('/app/orders/'+o.id)}><div className="mobile-order-top"><strong>{o.model}</strong><Badge tone={stateTone(orderState(o))} dot>{orderState(o)}</Badge></div><div className="mobile-order-bottom"><span>{c?.name} · {dateFR(o.due_date,{day:'numeric',month:'short'})}</span><strong>{money(o.price)}</strong></div></button>})}</div>
   </Card>
  </div><div className="dash-side">
   <Card className="production-overview"><PanelHead title="Production" subtitle="Où en sont vos commandes ?" action={<button className="icon-link" onClick={()=>navigate('/app/production')} aria-label="Voir la production"><ArrowUpRight size={19}/></button>}/><div className="production-total"><span>{active.length}</span><div>commandes<br/>en cours</div></div><div className="production-bars">{stages.map((s,i)=>{const n=active.filter(o=>o.stage===i).length;return <button className="production-bar-row" key={s} onClick={()=>navigate('/app/production')}><span className="stage-name">{s}</span><span className="stage-track"><span style={{width:active.length?`${Math.max(n/active.length*100,n?8:0)}%`:'0%',backgroundColor:stageColors[i]}}/></span><strong>{n}</strong></button>})}</div></Card>
   <Card className="side-action-card"><div className="side-action-icon"><CalendarCheck size={21}/></div><div><strong>{appointments.length?`${appointments.length} demande${appointments.length>1?'s':''} de rendez-vous`:'Vos rendez-vous'}</strong><p>{appointments.length?'Des visiteurs souhaitent vous rencontrer.':'Votre vitrine peut recevoir des demandes de RDV.'}</p><button onClick={()=>navigate('/app/showcase')}>Gérer les demandes <ArrowRight size={15}/></button></div></Card>
   {lowFabrics.length>0&&<Card className="low-stock-card"><div className="low-stock-head"><Boxes size={18}/><strong>Stock à surveiller</strong><Badge tone="amber">{lowFabrics.length}</Badge></div><p>{lowFabrics.slice(0,2).map(f=>f.name).join(', ')} {lowFabrics.length>2&&`et ${lowFabrics.length-2} autre${lowFabrics.length>3?'s':''}`} bientôt épuisé{lowFabrics.length>1?'s':''}.</p><button onClick={()=>navigate('/app/stock')}>Voir le stock <ArrowRight size={15}/></button></Card>}
   <div className="showcase-promo-card"><img src="/assets/gallery-style.jpg" alt="Création sur mesure à l'atelier"/><div className="showcase-promo-overlay"><span><Sparkles size={15}/> VOTRE VITRINE</span><h3>Votre savoir-faire mérite d’être vu.</h3><a href={orgPublicPath(data)} target="_blank" rel="noreferrer">Découvrir ma page <ArrowUpRight size={16}/></a></div></div>
  </div></div>
 </>;
}
