import React,{useState} from 'react';
import {Plus, Layers3, Scissors, Ruler, ChevronRight, CalendarDays, Clock3, GripVertical, LibraryBig, Sparkles, ArrowRight, Check, ClipboardList, UsersRound, CircleAlert, BookOpen, PackageCheck} from 'lucide-react';
import {useApp} from '../App.jsx';
import {PageHeader,Card,PanelHead,Button,Badge,Avatar,Modal,Input,Select,FormActions,Empty,Tabs} from '../components.jsx';
import {stages,stageColors,dateFR,today,uuid} from '../utils.js';

export default function Production(){
 const {data,branch,mutate,notify,navigate}=useApp(),[tab,setTab]=useState('kanban'),[newPattern,setNewPattern]=useState(false),[dragged,setDragged]=useState(null),[filter,setFilter]=useState('all');
 const orders=data.orders.filter(o=>o.status==='active'&&(branch==='all'||o.branch_id===branch)&&(filter==='all'||filter==='mine'&&o.assigned_user_id===data.user.id||filter==='urgent'&&o.due_date<=today()));
 const advance=async(order,stage)=>{try{await mutate('PATCH','/api/orders/'+order.id,{version:order.version,stage},old=>({...old,orders:old.orders.map(o=>o.id===order.id?{...o,stage,version:o.version+1}:o)}));notify('Étape de production mise à jour.');}catch(e){notify(e.message,'error')}};
 return <><PageHeader eyebrow="SUIVI DE CONFECTION" title="Production" subtitle="Visualisez chaque création et faites-la avancer d’un geste." action={['owner','tailor'].includes(data.user.role)&&<Button icon={Plus} onClick={()=>navigate('/app/orders?new=1')}>Nouvelle commande</Button>}/>
 <div className="production-topline"><Tabs items={[{key:'kanban',label:'Vue des étapes'},{key:'patterns',label:'Bibliothèque de patrons',count:data.patterns.length}]} active={tab} onChange={setTab}/>{tab==='kanban'?<div className="segmented"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Toutes</button><button className={filter==='mine'?'active':''} onClick={()=>setFilter('mine')}>Mes tâches</button><button className={filter==='urgent'?'active':''} onClick={()=>setFilter('urgent')}>Urgentes</button></div>:['owner','tailor'].includes(data.user.role)&&<Button size="sm" icon={Plus} onClick={()=>setNewPattern(true)}>Ajouter un patron</Button>}</div>
 {tab==='kanban'?<><div className="kanban-tip"><GripVertical size={15}/> Glissez une commande dans la colonne suivante ou utilisez le bouton « Étape suivante ».</div><div className="kanban-board">{stages.map((stage,i)=>{const cards=orders.filter(o=>o.stage===i);return <div className="kanban-column" key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged&&dragged.stage!==i){if(data.user.role==='apprentice'&&i!==dragged.stage+1)notify('Passez à l’étape suivante une par une.','error');else advance(dragged,i);}setDragged(null);}}><div className="kanban-head"><div className="kanban-head-left"><span className="kanban-dot" style={{background:stageColors[i]}}/><strong>{stage}</strong></div><span>{cards.length}</span></div><div className="kanban-cards">{cards.map(o=>{const client=data.clients.find(c=>c.id===o.client_id),late=o.due_date<today();return <div className="kanban-card" key={o.id} draggable onDragStart={e=>{setDragged(o);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',o.id)}} onDragEnd={()=>setDragged(null)}><div className="kanban-card-top"><small>{o.reference}</small>{late?<Badge tone="red">En retard</Badge>:o.due_date===today()?<Badge tone="amber">Aujourd’hui</Badge>:null}</div><button className="kanban-title" onClick={()=>navigate('/app/orders/'+o.id)}>{o.model}</button><div className="kanban-client"><Avatar name={client?.name} size="xs"/><span>{client?.name}</span></div><div className="kanban-card-footer"><span className={late?'late':''}><CalendarDays size={14}/>{dateFR(o.due_date,{day:'numeric',month:'short'})}</span>{i<4&&data.user.role!=='accountant'?<button title="Étape suivante" aria-label={'Passer '+o.model+' à '+stages[i+1]} onClick={()=>advance(o,i+1)}><ArrowRight size={16}/></button>:<button title="Voir la commande" onClick={()=>navigate('/app/orders/'+o.id)}><ChevronRight size={16}/></button>}</div></div>})}{!cards.length&&<div className="kanban-empty">Aucune commande<br/>à cette étape</div>}</div></div>})}</div></>:<div className="patterns-grid">{data.patterns.map(p=><Card className="pattern-card" key={p.id}><span className="pattern-icon"><Scissors size={23}/></span><Badge tone="mint">{p.garment_type||'Patron'}</Badge><h3>{p.name}</h3><p>{p.description||'Un modèle réutilisable pour vos prochaines créations.'}</p><div className="pattern-foot"><span>Patron réutilisable</span>{['owner','tailor'].includes(data.user.role)&&<button onClick={()=>navigate('/app/orders?new=1')}>Créer une commande <ArrowRight size={15}/></button>}</div></Card>)}{['owner','tailor'].includes(data.user.role)&&<button className="pattern-create" onClick={()=>setNewPattern(true)}><span><Plus size={22}/></span><strong>Nouveau patron</strong><small>Gardez vos coupes préférées à portée de main.</small></button>}</div>}
 {newPattern&&<PatternForm onClose={()=>setNewPattern(false)}/>}
 </>;
}
function PatternForm({onClose}){const {mutate,notify}=useApp(),[form,setForm]=useState({name:'',garment_type:'Robe',description:''}),[busy,setBusy]=useState(false);const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);const id=uuid(),body={id,...form};try{await mutate('POST','/api/patterns',body,old=>({...old,patterns:[{...body,created_at:new Date().toISOString()},...old.patterns]}));notify('Patron ajouté à la bibliothèque.');onClose();}catch(e){notify(e.message,'error')}finally{setBusy(false)}};return <Modal title="Nouveau patron" subtitle="Une coupe à réutiliser pour les prochaines commandes." onClose={onClose}><form className="form-stack" onSubmit={submit}><Input label="Nom du patron" placeholder="Ex. Robe princesse manches bouffantes" name="name" value={form.name} onChange={change} required/><Select label="Type de vêtement" name="garment_type" value={form.garment_type} onChange={change}>{['Robe','Ensemble','Boubou','Tailleur','Chemise','Jupe','Pantalon','Autre'].map(x=><option key={x}>{x}</option>)}</Select><Input as="textarea" rows={4} label="Détails de la coupe" name="description" placeholder="Taille, coupe, finitions, petits secrets..." value={form.description} onChange={change}/><FormActions onCancel={onClose} loading={busy} label="Enregistrer le patron"/></form></Modal>}
