import React,{useEffect,useState} from 'react';
import {Scissors, ArrowUpRight, ArrowRight, MessageCircle, MapPin, Star, CalendarDays, Instagram, Phone, Clock3, Sparkles, Menu, X, Check, ChevronRight, MoveUpRight, Heart, Ruler, ExternalLink, LoaderCircle} from 'lucide-react';
import {useApp} from '../App.jsx';
import {Modal,Input,Button,FormActions,Loading} from '../components.jsx';
import {waLink,money,today} from '../utils.js';
export default function PublicSite({slug}){const {data:appData,request,notify,navigate}=useApp(),[site,setSite]=useState(appData?.organization?.slug===slug?{organization:appData.organization,showcase:appData.showcase,reviews:appData.reviews,branches:appData.branches}:null),[loading,setLoading]=useState(!site),[appointment,setAppointment]=useState(false),[menu,setMenu]=useState(false);
 useEffect(()=>{setLoading(!site);request('/api/public/'+encodeURIComponent(slug)).then(r=>{setSite(r);setLoading(false)}).catch(e=>{setLoading(false);if(!site)notify(e.message,'error')});},[slug]);
 if(loading&&!site)return <Loading/>;
 if(!site)return <div className="public-not-found"><span><Scissors size={30}/></span><h1>Atelier introuvable</h1><p>Cette vitrine n’est pas disponible pour le moment.</p><button onClick={()=>navigate('/app')}>Retour à KouturePro <ArrowRight size={17}/></button></div>;
 const o=site.organization,hasPhotos=site.showcase.length>0,cover=o.cover_url||'/assets/atelier-hero.jpg';const goWhatsapp=waLink(o.whatsapp_phone,`Bonjour ${o.name}, je voudrais en savoir plus sur vos créations.`);
 return <div className="public-site"><div className="public-topline"><span><MapPin size={13}/>{o.city}, Côte d’Ivoire</span><span>Votre style, notre savoir-faire.</span><a href={goWhatsapp} target="_blank" rel="noreferrer"><MessageCircle size={13}/> Discutons sur WhatsApp</a></div>
 <header className="public-header"><a className="public-logo" href="#accueil"><span>{o.logo_url?<img src={o.logo_url} alt={"Logo "+o.name}/>:<Scissors size={21}/>}</span><span><strong>{o.name}</strong><small>MAISON DE COUTURE</small></span></a><nav className={menu?'open':''}><a href="#savoir-faire" onClick={()=>setMenu(false)}>Notre atelier</a><a href="#realisations" onClick={()=>setMenu(false)}>Réalisations</a><a href="#avis" onClick={()=>setMenu(false)}>Vos mots</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav><div className="public-header-actions"><button onClick={()=>setAppointment(true)} className="public-header-cta">Prendre rendez-vous <ArrowUpRight size={16}/></button><button className="public-menu-button" aria-label={menu?'Fermer le menu':'Ouvrir le menu'} onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button></div></header>
 <section className="public-hero" id="accueil"><img src={cover} alt={'L’atelier de couture '+o.name} fetchPriority="high"/><div className="public-hero-shade"/><div className="public-hero-content"><span className="public-eyebrow"><i/> COUTURE SUR MESURE · {o.city.toUpperCase()}</span><h1>L’élégance<br/>se dessine <em>sur mesure.</em></h1><p>{o.description||'Un atelier où chaque création raconte votre histoire.'}</p><div className="public-hero-actions"><button onClick={()=>setAppointment(true)} className="public-btn public-btn-light">Prendre rendez-vous <ArrowUpRight size={17}/></button><a href="#realisations" className="public-btn public-btn-outline">Voir nos créations <ArrowRight size={17}/></a></div></div><div className="public-hero-side">CRÉATIONS UNIQUES <span>✦</span> FAIT AVEC AMOUR</div><div className="hero-bottom-tag"><span>01 — L’ART DE CRÉER POUR VOUS</span><span>Défiler pour découvrir <span>↓</span></span></div></section>
 <div className="public-value-strip"><div><span>01</span><strong>À votre mesure</strong><small>Chaque détail compte</small></div><div><span>02</span><strong>Fait avec soin</strong><small>Par des mains passionnées</small></div><div><span>03</span><strong>Comme vous</strong><small>Une pièce, une histoire</small></div></div>
 <section className="public-story" id="savoir-faire"><div className="story-image-wrap"><img src="/assets/gallery-studio.jpg" loading="lazy" alt="Mains d'un artisan tailleur coupant un tissu"/><span className="story-image-stamp"><Scissors size={24}/><span>L’ART DU<br/>SUR-MESURE</span></span></div><div className="story-text"><span className="public-section-kicker">NOTRE SAVOIR-FAIRE <i/></span><h2>Plus qu’un vêtement,<br/><em>une histoire à porter.</em></h2><p>Chez {o.name}, nous croyons qu’une tenue peut tout changer. Nous prenons le temps d’écouter vos envies, de comprendre votre silhouette et de donner vie à la création qui vous ressemble.</p><div className="story-points"><div><span><Ruler size={20}/></span><div><strong>Une coupe pensée pour vous</strong><small>Vos mesures, votre confort, votre allure.</small></div></div><div><span><Heart size={20}/></span><div><strong>Le soin dans chaque détail</strong><small>De la première esquisse à la dernière finition.</small></div></div></div><button className="public-text-link" onClick={()=>setAppointment(true)}>Imaginons votre tenue ensemble <ArrowUpRight size={17}/></button></div></section>
 <section className="public-specialties"><div><span className="public-section-kicker">CE QUE NOUS AIMONS CRÉER</span><h2>La beauté de <em>chaque occasion.</em></h2></div><div className="public-specialty-tags">{o.specialties.length?o.specialties.map((s,i)=><span key={s}><small>0{i+1}</small> {s} <ArrowUpRight size={16}/></span>):['Créations sur mesure','Tenues uniques','Votre histoire'].map((s,i)=><span key={s}><small>0{i+1}</small> {s} <ArrowUpRight size={16}/></span>)}</div></section>
 <section className="public-gallery" id="realisations"><div className="public-section-heading"><div><span className="public-section-kicker">LE PORTFOLIO</span><h2>Nos créations, <em>vos histoires.</em></h2><p>Quelques pièces imaginées avec vous et confectionnées avec soin.</p></div><span className="gallery-asterisk">✳</span></div><div className="public-gallery-grid">{(hasPhotos?site.showcase:[{id:'sample1',title:'Le savoir-faire',image_url:'/assets/gallery-studio.jpg',description:'Chaque détail compte.'}]).map((item,i)=><div className={'public-gallery-card gallery-'+i%3} key={item.id}><div className="public-gallery-photo"><img src={item.image_url} loading="lazy" alt={item.title}/><span className="gallery-index">0{i+1}</span></div><div className="public-gallery-caption"><div><strong>{item.title}</strong><span>{item.description}</span></div><span><ArrowUpRight size={18}/></span></div></div>)}</div><div className="gallery-bottom-line"><span>Des pièces qui n’appartiennent qu’à vous.</span><button onClick={()=>setAppointment(true)}>Parlons de votre projet <ArrowRight size={16}/></button></div></section>
 <section className="public-testimonials" id="avis"><div className="testimonials-top"><span className="public-section-kicker">VOS MOTS, NOTRE PLUS BELLE RÉCOMPENSE</span><span>★★★★★</span></div><h2>Des créations aimées.<br/><em>Des histoires partagées.</em></h2><div className="testimonials-grid">{site.reviews.slice(0,3).map((r,i)=><div className="testimonial-card" key={r.id}><span className="quote-mark">“</span><p>{r.text}</p><div><span>{'★'.repeat(r.rating)}</span><strong>{r.name}</strong></div></div>)}{!site.reviews.length&&<p className="no-reviews">Les histoires de nos clients prendront bientôt place ici.</p>}</div></section>
 <section className="public-contact" id="contact"><div className="contact-copy"><span className="public-section-kicker">VOTRE PROCHAINE CRÉATION COMMENCE ICI</span><h2>Et si on imaginait<br/><em>la vôtre ensemble ?</em></h2><p>Une envie, une idée, une occasion spéciale ? Poussez la porte de notre atelier. Nous serons heureux de vous rencontrer.</p><div className="contact-actions"><button onClick={()=>setAppointment(true)} className="public-btn public-btn-dark">Prendre rendez-vous <ArrowUpRight size={17}/></button><a href={goWhatsapp} target="_blank" rel="noreferrer" className="public-btn public-btn-white"><MessageCircle size={18}/> Écrire sur WhatsApp</a></div></div><div className="contact-location"><span className="location-decoration"><MapPin size={32}/></span><div><span>VENEZ NOUS RENDRE VISITE</span><h3>{o.name}</h3><p>{[o.address,o.neighborhood,o.city].filter(Boolean).join(', ')}</p><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([o.address,o.city].filter(Boolean).join(' '))} target="_blank" rel="noreferrer">Itinéraire <ArrowUpRight size={15}/></a></div><div className="location-pattern">✳</div></div></section>
 <footer className="public-footer"><div className="public-footer-top"><div><a href="#accueil" className="public-logo footer-logo"><span>{o.logo_url?<img src={o.logo_url} alt={"Logo "+o.name}/>:<Scissors size={21}/>}</span><span><strong>{o.name}</strong><small>MAISON DE COUTURE</small></span></a><p>Le sur-mesure, pour les moments qui comptent.</p></div><div><strong>DÉCOUVRIR</strong><a href="#savoir-faire">Notre atelier</a><a href="#realisations">Réalisations</a><a href="#avis">Avis clients</a></div><div><strong>NOUS TROUVER</strong><span>{o.city}, Côte d’Ivoire</span><a href={goWhatsapp} target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={13}/></a><button onClick={()=>setAppointment(true)}>Prendre rendez-vous</button></div></div><div className="public-footer-bottom"><span>© {new Date().getFullYear()} {o.name}. Créé avec passion.</span><span>Propulsé par <a href="/app">KouturePro</a> <Scissors size={13}/></span></div></footer>
 {appointment&&<AppointmentForm slug={slug} org={o} onClose={()=>setAppointment(false)}/>}
 </div>;
}
function AppointmentForm({slug,org,onClose}){const {request,notify}=useApp(),[form,setForm]=useState({name:'',phone:'',preferred_date:'',message:''}),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);try{await request('/api/public/'+encodeURIComponent(slug)+'/appointments',{method:'POST',body:form});setSent(true);notify('Votre demande a été envoyée à l’atelier.');}catch(e){notify(e.message,'error')}finally{setBusy(false)}};return <Modal title={sent?'Demande envoyée !':'Prenons rendez-vous'} subtitle={sent?"L’atelier vous recontactera pour confirmer.":'Quelques mots suffisent pour commencer votre création.'} onClose={onClose}>{sent?<div className="appointment-success"><span><Check size={30}/></span><h3>Merci pour votre confiance.</h3><p>{org.name} a bien reçu votre demande. À très bientôt !</p><Button onClick={onClose}>Terminer</Button></div>:<form className="form-stack" onSubmit={submit}><Input label="Votre nom" name="name" value={form.name} onChange={change} required placeholder="Comment vous appeler ?"/><Input label="Votre téléphone" name="phone" type="tel" value={form.phone} onChange={change} required placeholder="+225 ..."/><Input label="Date souhaitée" name="preferred_date" type="date" min={today()} value={form.preferred_date} onChange={change} required/><Input label="Votre idée (facultatif)" name="message" as="textarea" rows={3} value={form.message} onChange={change} placeholder="Une tenue, une occasion, une question..."/><div className="form-actions"><Button type="button" variant="soft" onClick={onClose}>Annuler</Button><Button type="submit" loading={busy}>Envoyer ma demande <ArrowRight size={16}/></Button></div></form>}</Modal>}
