import React,{useState} from 'react';
import {Settings2, Store, Bell, Wifi, WifiOff, CloudUpload, ShieldCheck, Smartphone, MessageCircle, CreditCard, ChevronRight, Check, CircleAlert, Info, Sparkles, Zap, LifeBuoy, Link2, ExternalLink, RotateCcw, LockKeyhole, HardDrive, Crown, FileText, Phone, ArrowRight} from 'lucide-react';
import {useApp} from '../App.jsx';
import {PageHeader,Card,PanelHead,Button,Badge,Avatar,Input,Modal} from '../components.jsx';
import {orgPublicPath} from '../utils.js';
export default function Settings(){const {data,online,forcedOffline,simulateOffline,pending,syncing,syncQueue,mutate,notify,navigate,logout}=useApp(),o=data.organization,[saving,setSaving]=useState(false),[passwordOpen,setPasswordOpen]=useState(false);
 const toggle=async(key)=>{setSaving(true);try{const next=!o[key];await mutate('PATCH','/api/organization',{[key]:next},old=>({...old,organization:{...old.organization,[key]:next?1:0}}));notify(next?'Rappels activés.':'Rappels désactivés.');}catch(e){notify(e.message,'error')}finally{setSaving(false)}};
 return <><PageHeader eyebrow="VOTRE ESPACE" title="Paramètres" subtitle="Toutes les préférences de votre atelier, réunies ici."/>
 <div className="settings-layout"><div className="settings-primary"><Card className="settings-card"><PanelHead title="Informations de l’atelier" subtitle="La base de votre espace KouturePro" icon={Store}/><div className="setting-org"><span className="setting-org-logo">{o.name[0]}</span><div><strong>{o.name}</strong><small>{o.city} · {o.slug}</small></div><Badge tone="mint">Plan {o.plan==='business'?'Business':o.plan==='pro'?'Pro':'Starter'}</Badge></div><div className="settings-row"><span><Store size={19}/></span><div><strong>Ma vitrine publique</strong><small>Vos créations sont accessibles en ligne.</small></div><a href={orgPublicPath(data)} target="_blank" rel="noreferrer"><ExternalLink size={17}/></a></div><div className="settings-row"><span><Phone size={19}/></span><div><strong>WhatsApp professionnel</strong><small>{o.whatsapp_phone||'À renseigner dans votre vitrine'}</small></div><button onClick={()=>navigate('/app/showcase')}>Modifier <ChevronRight size={16}/></button></div><div className="settings-row"><span><Crown size={19}/></span><div><strong>Votre abonnement</strong><small>{o.plan==='business'?'Business':o.plan==='pro'?'Pro':'Starter'} · Devise : FCFA (XOF)</small></div><Badge tone={o.is_demo?'gray':'mint'}>{o.is_demo?'Démo':o.plan==='starter'?'Plan de départ':'Plan actif'}</Badge></div></Card>
 <Card className="settings-card"><PanelHead title="Rappels automatiques désactivés" subtitle="Aucun message n’est envoyé par une API" icon={Bell}/><div className="settings-help"><Info size={17}/> Les anciennes préférences WhatsApp et SMS sont conservées, mais aucun rappel automatique n’est envoyé. Dans l’espace marchand, les messages sont partagés manuellement et uniquement avec l’accord enregistré du client.</div></Card>
 <Card className="settings-card"><PanelHead title="Hors ligne & synchronisation" subtitle="Continuez à travailler même avec une connexion capricieuse" icon={CloudUpload}/><div className="sync-status-large"><span className={'sync-large-icon '+(!online?'offline':'')} >{online?<Wifi size={25}/>:<WifiOff size={25}/>}</span><div><strong>{!online?'Vous travaillez hors ligne':syncing?'Synchronisation en cours':pending?'Des modifications sont en attente':'Tout est synchronisé'}</strong><p>{!online?"Vos saisies sont sauvegardées sur cet appareil. Elles seront envoyées quand la connexion reviendra.":pending?`${pending} modification${pending>1?'s':''} encore à synchroniser.`:'Les dernières données de votre atelier sont disponibles sur cet appareil.'}</p></div><Badge tone={online?'green':'amber'}>{online?'Connecté':'Hors ligne'}</Badge></div><div className="settings-row"><span><WifiOff size={19}/></span><div><strong>Simuler le mode hors ligne</strong><small>Essayez l’application sans réseau, puis vérifiez la synchronisation.</small></div><button className={'toggle '+(forcedOffline?'on':'')} role="switch" aria-checked={forcedOffline} aria-label="Simuler hors ligne" onClick={()=>simulateOffline(!forcedOffline)}><i/></button></div><Button variant="soft" icon={RotateCcw} onClick={syncQueue} disabled={!online||syncing}>{syncing?'Synchronisation...':'Synchroniser maintenant'}{pending>0?` (${pending})`:''}</Button><div className="settings-help"><Info size={17}/> Vous pouvez saisir clients, mesures, commandes, paiements en espèces et dépenses hors ligne. Les liens de paiement manuel exigent internet ; aucun envoi automatique de message n’est réalisé.</div></Card>
 <Card className="settings-card"><PanelHead title="Paiements manuels" subtitle="Sans CinetPay, WhatsApp Business API ni Twilio" icon={CreditCard}/><div className="settings-help"><ShieldCheck size={17}/> L’espace marchand permet de recevoir un paiement réel sur votre numéro, d’enregistrer une référence et de confirmer le paiement vous-même. Vos anciennes commandes d’atelier restent conservées ici.</div><a className="btn btn-soft" href="/marchands">Ouvrir l’espace marchand <ArrowRight size={17}/></a></Card><Card className="settings-card"><PanelHead title="Sécurité du compte" subtitle="Vos identifiants restent privés" icon={LockKeyhole}/><div className="settings-row"><span><LockKeyhole size={19}/></span><div><strong>Mot de passe</strong><small>Modifiez-le régulièrement et ne le communiquez à personne.</small></div><button onClick={()=>setPasswordOpen(true)}>Modifier <ChevronRight size={16}/></button></div></Card></div>
 <div className="settings-secondary"><Card className="settings-profile"><Avatar name={data.user.name} size="xl"/><h3>{data.user.name}</h3><p>{data.user.phone||data.user.email}</p><Badge tone="mint">{data.user.role==='owner'?'Propriétaire':data.user.role==='tailor'?'Couturier':data.user.role==='accountant'?'Comptable':'Apprenti'}</Badge><div><ShieldCheck size={17}/> Mesures chiffrées sur le serveur</div><div><HardDrive size={17}/> Données enregistrées dans la base de l’atelier</div></Card><div className="settings-tip"><Sparkles size={24}/><h3>Un atelier serein.</h3><p>Votre travail reste à portée de main, même quand le réseau prend une pause.</p><button onClick={()=>navigate('/app/showcase')}>Soigner ma vitrine <ArrowRight size={16}/></button></div><button className="logout-btn" onClick={logout}>Se déconnecter <ArrowRight size={16}/></button></div></div>
 {passwordOpen&&<PasswordModal onClose={()=>setPasswordOpen(false)}/>}
 </>;
}

function PasswordModal({onClose}){
 const {request,notify}=useApp(),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();if(password!==confirmation){notify('Les nouveaux mots de passe ne correspondent pas.','error');return;}setBusy(true);
  try{await request('/api/auth/change-password',{method:'POST',body:{current_password:current,new_password:password}});notify('Mot de passe changé. Vos autres sessions sont déconnectées.');onClose();}
  catch(err){notify(err.message,'error');}finally{setBusy(false);}};
 return <Modal title="Changer mon mot de passe" subtitle="Protégez l’accès à votre atelier" onClose={onClose}><form className="form-stack" onSubmit={submit}>
  <Input label="Mot de passe actuel" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/>
  <Input label="Nouveau mot de passe" type="password" autoComplete="new-password" minLength={10} maxLength={72} value={password} onChange={e=>setPassword(e.target.value)} required hint="Au moins 10 caractères."/>
  <Input label="Confirmer le nouveau mot de passe" type="password" autoComplete="new-password" minLength={10} maxLength={72} value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/>
  <div className="form-actions"><Button variant="soft" type="button" onClick={onClose}>Annuler</Button><Button type="submit" loading={busy}>Enregistrer le mot de passe</Button></div>
 </form></Modal>;
}
