import React,{useMemo,useState} from 'react';
import {ChartNoAxesCombined, TrendingUp, ShoppingBag, UsersRound, Clock3, Sparkles, Layers3, ArrowUpRight, CalendarDays, CircleAlert, Boxes, Info, ChevronRight, Target, BadgeCheck, BarChart3} from 'lucide-react';
import {useApp} from '../App.jsx';
import {PageHeader,Card,PanelHead,Button,Badge,Avatar,StatCard,Empty} from '../components.jsx';
import {money,fmt,shortMoney,dateFR,today,stages} from '../utils.js';
function monthsBack(n){return Array.from({length:n},(_,i)=>{const d=new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth()-(n-1-i),12));return {key:d.toISOString().slice(0,7),name:new Intl.DateTimeFormat('fr-FR',{month:'short',timeZone:'UTC'}).format(d)}})}
export default function Stats(){const {data,branch,navigate}=useApp(),[period,setPeriod]=useState(6);const orders=data.orders.filter(o=>branch==='all'||o.branch_id===branch),ids=new Set(orders.map(o=>o.id)),paid=data.payments.filter(p=>ids.has(p.order_id)&&p.status==='paid'),months=monthsBack(period).map(m=>({...m,total:paid.filter(p=>p.created_at.slice(0,7)===m.key).reduce((a,p)=>a+p.amount,0)}));
 const total=paid.reduce((a,p)=>a+p.amount,0),finished=orders.filter(o=>o.status==='delivered'),onTime=finished.filter(o=>!o.delivered_at||o.delivered_at.slice(0,10)<=o.due_date),late=orders.filter(o=>o.status==='active'&&o.due_date<today()),categories=Object.entries(orders.reduce((acc,o)=>{acc[o.garment_type]=(acc[o.garment_type]||0)+1;return acc},{})).sort((a,b)=>b[1]-a[1]).slice(0,5),topClients=data.clients.map(c=>({...c,total:paid.filter(p=>orders.find(o=>o.id===p.order_id&&o.client_id===c.id)).reduce((a,p)=>a+p.amount,0),n:orders.filter(o=>o.client_id===c.id).length})).filter(c=>c.n>0).sort((a,b)=>b.total-a.total).slice(0,4);
 const recentUsage=data.orders.filter(o=>o.fabric_id&&o.created_at>=new Date(Date.now()-90*864e5).toISOString()).reduce((acc,o)=>{acc[o.fabric_id]=(acc[o.fabric_id]||0)+Number(o.fabric_quantity||0);return acc},{}),fabricForecast=data.fabrics.filter(f=>recentUsage[f.id]>0).map(f=>({name:f.name,average:recentUsage[f.id]/3,available:f.quantity,cover:recentUsage[f.id]?f.quantity/(recentUsage[f.id]/3):null})).sort((a,b)=>a.cover-b.cover).slice(0,3),profit=orders.filter(o=>o.status==='delivered').reduce((a,o)=>a+o.price-(o.material_cost||0)-(o.commission||0),0);
 return <><PageHeader eyebrow="PRENDRE DU RECUL" title="Statistiques" subtitle="Comprenez ce qui marche et préparez les prochaines créations."/>
 <div className="stats-grid"><StatCard label="Total encaissé" value={money(total)} sub="sur l’historique enregistré" icon={TrendingUp} tone="green"/><StatCard label="Commandes livrées" value={fmt(finished.length)} sub="depuis la création de l’atelier" icon={ShoppingBag} tone="blue"/><StatCard label="Livrées à temps" value={finished.length?Math.round(onTime.length/finished.length*100)+' %':'—'} sub={`${onTime.length} sur ${finished.length} commandes livrées`} icon={Clock3} tone="purple"/><StatCard label="Marge estimée" value={money(profit)} sub="commandes livrées, hors charges" icon={Target} tone="amber"/></div>
 <div className="stats-main-grid"><Card className="revenue-chart-card"><PanelHead title="Évolution des encaissements" subtitle="Paiements réellement confirmés, mois par mois" icon={ChartNoAxesCombined} action={<div className="segmented"><button className={period===6?'active':''} onClick={()=>setPeriod(6)}>6 mois</button><button className={period===12?'active':''} onClick={()=>setPeriod(12)}>12 mois</button></div>}/><div className="revenue-total">{money(months.at(-1)?.total||0)}<span>ce mois-ci</span></div><RevenueBars months={months}/></Card><Card className="category-chart-card"><PanelHead title="Les créations préférées" subtitle="Selon vos commandes" icon={Layers3}/>{categories.map(([name,n],i)=><div className="category-row" key={name}><div><span className="category-color" style={{background:['#227655','#769bb2','#b7a174','#aaa3be','#cc8f7d'][i]}}/>{name}<strong>{n}</strong></div><span className="category-track"><span style={{width:(n/(orders.length||1)*100)+'%',background:['#227655','#769bb2','#b7a174','#aaa3be','#cc8f7d'][i]}}/></span></div>)}{!categories.length&&<Empty icon={Layers3} title="Aucune commande" description="Les créations les plus demandées apparaîtront ici."/>}</Card></div>
 <div className="stats-bottom-grid"><Card className="top-clients-card"><PanelHead title="Vos clients fidèles" subtitle="Ceux qui aiment revenir à l’atelier" icon={UsersRound}/>{topClients.map((c,i)=><button className="top-client-row" key={c.id} onClick={()=>navigate('/app/clients?client='+c.id)}><span className="client-rank">{String(i+1).padStart(2,'0')}</span><Avatar name={c.name} color={i} size="sm"/><span><strong>{c.name}</strong><small>{c.n} commande{c.n>1?'s':''}</small></span><strong>{money(c.total)}</strong><ChevronRight size={16}/></button>)}{!topClients.length&&<Empty icon={UsersRound} title="Vos clients bientôt ici" description="Créez votre première commande pour commencer."/>}</Card><Card className="forecast-card"><PanelHead title="À prévoir pour votre stock" subtitle="Repères calculés à partir des 90 derniers jours" icon={Sparkles}/><div className="forecast-note"><Info size={16}/><span>Estimation simple basée sur l’usage moyen mensuel, pas une promesse de vente.</span></div>{fabricForecast.map(f=><div className="forecast-row" key={f.name}><span className={'forecast-icon '+(f.cover<1?'risk':'')}><Boxes size={18}/></span><span><strong>{f.name}</strong><small>≈ {f.average.toFixed(1).replace('.',',')} m utilisés / mois</small></span><Badge tone={f.cover<1?'red':f.cover<2?'amber':'green'}>{f.cover<1?'À acheter':`≈ ${f.cover.toFixed(1).replace('.',',')} mois`}</Badge></div>)}{!fabricForecast.length&&<Empty icon={Boxes} title="Pas encore assez de données" description="Les achats prévisionnels apparaîtront après quelques commandes avec tissu de l’atelier."/>}<div className="forecast-season"><CalendarDays size={19}/><div><strong>Repère saisonnier</strong><p>Fêtes, rentrée et mariages peuvent créer des pics. Comparez les mêmes périodes d’une année à l’autre lorsque vous aurez assez d’historique.</p></div></div></Card></div>
 </>;
}
function RevenueBars({months}){const max=Math.max(...months.map(x=>x.total),1);return <div className="revenue-chart"><div className="revenue-grid"><span>{shortMoney(max)}</span><span>{shortMoney(max*.5)}</span><span>0</span></div><div className="revenue-bars">{months.map((m,i)=><div className="revenue-bar-wrap" key={m.key}><div className="revenue-bar-track"><span className={i===months.length-1?'current':''} style={{height:(m.total?Math.max(5,m.total/max*100):1)+'%'}} title={`${m.name} : ${money(m.total)}`}/></div><small>{m.name.replace('.','')}</small></div>)}</div></div>}
