import React,{useState} from 'react';
import {Plus, Boxes, PackagePlus, CircleAlert, Truck, Search, ChevronRight, Layers3, ArrowUpRight, Phone, MapPin, ShoppingCart, ReceiptText, Package, Minus, Info, ShoppingBag, CalendarDays} from 'lucide-react';
import {useApp} from '../App.jsx';
import {PageHeader,Card,PanelHead,Button,Badge,Tabs,Modal,Input,Select,FormActions,SearchInput,Empty} from '../components.jsx';
import {money,dateFR,uuid,fmt} from '../utils.js';

const swatches={Indigo:'#394f78',Ivoire:'#e8ddc5',Émeraude:'#397e67',Sable:'#d9c09a',Rouge:'#bf5b57',Bleu:'#648db0',Noir:'#374248',Blanc:'#f3f1e8'};
export default function Stock(){const {data,branch,navigate}=useApp(),[tab,setTab]=useState('fabrics'),[search,setSearch]=useState(''),[addFabric,setAddFabric]=useState(false),[addSupplier,setAddSupplier]=useState(false),[buyFabric,setBuyFabric]=useState(null),[selectedSupplier,setSelectedSupplier]=useState(null);
 const canManageStock=['owner','accountant'].includes(data.user.role);
 const branchFabrics=data.fabrics.filter(f=>branch==='all'||f.branch_id===branch),fabrics=branchFabrics.filter(f=>f.name.toLowerCase().includes(search.toLowerCase())),low=branchFabrics.filter(f=>f.quantity<=f.threshold),qty=branchFabrics.reduce((a,f)=>a+f.quantity,0),stockValue=branchFabrics.reduce((a,f)=>a+f.quantity*f.unit_cost,0);
 const purchases=data.expenses.filter(e=>e.category==='Achat tissu'&&(branch==='all'||e.branch_id===branch)).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 return <><PageHeader eyebrow="TOUT SOUS LA MAIN" title="Stock & fournisseurs" subtitle="Vos tissus, vos achats et vos partenaires au même endroit." action={canManageStock&&<Button icon={Plus} onClick={()=>tab==='suppliers'?setAddSupplier(true):setAddFabric(true)}>{tab==='suppliers'?'Nouveau fournisseur':'Ajouter un tissu'}</Button>}/>
 <div className="stats-grid stock-stats"><Card className="stock-stat"><span className="stock-stat-icon mint"><Boxes size={20}/></span><div><small>RÉFÉRENCES EN STOCK</small><strong>{branchFabrics.length}</strong><span>tissus et matières</span></div></Card><Card className="stock-stat"><span className="stock-stat-icon blue"><Layers3 size={20}/></span><div><small>MÉTRAGE TOTAL</small><strong>{new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(qty)} m</strong><span>disponibles à l’atelier</span></div></Card><Card className="stock-stat"><span className="stock-stat-icon amber"><CircleAlert size={20}/></span><div><small>STOCK FAIBLE</small><strong>{low.length}</strong><span>à réapprovisionner</span></div></Card><Card className="stock-stat"><span className="stock-stat-icon purple"><ShoppingCart size={20}/></span><div><small>VALEUR DU STOCK</small><strong>{money(stockValue)}</strong><span>au coût d’achat estimé</span></div></Card></div>
 {low.length>0&&<div className="stock-warning"><CircleAlert size={19}/><div><strong>À prévoir : {low.map(x=>x.name).join(', ')}</strong><p>Ces tissus sont sous leur seuil d’alerte. Pensez à les réapprovisionner.</p></div>{canManageStock&&<button onClick={()=>setBuyFabric(low[0])}>Enregistrer un achat <ChevronRight size={16}/></button>}</div>}
 <div className="production-topline"><Tabs items={[{key:'fabrics',label:'Mes tissus',count:branchFabrics.length},{key:'suppliers',label:'Fournisseurs',count:data.suppliers.length},{key:'purchases',label:'Achats récents'}]} active={tab} onChange={setTab}/>{tab==='fabrics'&&<SearchInput value={search} onChange={setSearch} placeholder="Rechercher un tissu"/>}</div>
 {tab==='fabrics'&&<div className="fabric-grid">{fabrics.map(f=><Card className="fabric-card" key={f.id}><div className="fabric-header"><div className="fabric-swatch" style={{background:swatches[f.color]||'#91a997'}}><span/></div><Badge tone={f.quantity<=f.threshold?'amber':'green'} dot>{f.quantity<=f.threshold?'Stock faible':'En stock'}</Badge></div><h3>{f.name}</h3><p>{f.category} · {f.color||'Sans couleur'}</p><div className="fabric-quantity"><strong>{new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(f.quantity)} <small>{f.unit}</small></strong><span>disponibles</span></div><div className="fabric-divider"/><div className="fabric-meta"><span>Coût / {f.unit}</span><strong>{money(f.unit_cost)}</strong></div><div className="fabric-meta"><span>Seuil d’alerte</span><strong>{f.threshold} {f.unit}</strong></div>{canManageStock&&<button className="fabric-replenish" onClick={()=>setBuyFabric(f)}><PackagePlus size={17}/> Enregistrer un achat <ChevronRight size={16}/></button>}</Card>)}{canManageStock&&<button className="fabric-add-card" onClick={()=>setAddFabric(true)}><span><Plus size={24}/></span><strong>Ajouter un tissu</strong><small>Gardez votre stock bien organisé</small></button>}</div>}
 {tab==='suppliers'&&<div className="suppliers-grid">{data.suppliers.map(s=><Card className="supplier-card" key={s.id}><span className="supplier-icon"><Truck size={23}/></span><h3>{s.name}</h3><p>{s.city||'Ville non renseignée'}</p><div className="supplier-divider"/><div><Phone size={17}/><a href={'tel:'+s.phone}>{s.phone||'Pas de numéro'}</a></div><div><Boxes size={17}/><span>{data.fabrics.filter(f=>f.supplier_id===s.id).length} tissu{data.fabrics.filter(f=>f.supplier_id===s.id).length>1?'s':''} associé{data.fabrics.filter(f=>f.supplier_id===s.id).length>1?'s':''}</span></div><button className="supplier-history" onClick={()=>setSelectedSupplier(s)}>Voir les achats <ChevronRight size={16}/></button></Card>)}{canManageStock&&<button className="fabric-add-card" onClick={()=>setAddSupplier(true)}><span><Plus size={24}/></span><strong>Nouveau fournisseur</strong><small>Une adresse de plus dans votre carnet</small></button>}</div>}
 {tab==='purchases'&&<Card className="list-page-card"><PanelHead title="Achats de tissus" subtitle="Chaque achat ajoute automatiquement le métrage au stock" icon={ShoppingCart}/><div className="cash-list">{purchases.map(e=><div className="cash-row" key={e.id}><span className="cash-icon in"><PackagePlus size={19}/></span><span className="cash-row-main"><strong>{e.label}</strong><small>{dateFR(e.created_at)} · {e.quantity} m ajoutés</small></span><strong className="cash-amount">{money(e.amount)}</strong></div>)}{!purchases.length&&<Empty icon={ShoppingCart} title="Aucun achat de tissu" description="Les réapprovisionnements apparaîtront ici."/>}</div></Card>}
 {addFabric&&<FabricForm onClose={()=>setAddFabric(false)}/>} {addSupplier&&<SupplierForm onClose={()=>setAddSupplier(false)}/>} {buyFabric&&<PurchaseForm fabric={buyFabric} onClose={()=>setBuyFabric(null)}/>} {selectedSupplier&&<Modal title={selectedSupplier.name} subtitle="Historique des achats auprès de ce fournisseur" onClose={()=>setSelectedSupplier(null)}><div className="supplier-purchases">{data.expenses.filter(e=>e.supplier_id===selectedSupplier.id).map(e=><div key={e.id}><span><ShoppingCart size={18}/></span><div><strong>{e.label}</strong><small>{dateFR(e.created_at)} · {e.quantity} m</small></div><b>{money(e.amount)}</b></div>)}{!data.expenses.some(e=>e.supplier_id===selectedSupplier.id)&&<Empty icon={ShoppingCart} title="Aucun achat enregistré" description="Les achats faits auprès de ce fournisseur apparaîtront ici."/>}</div></Modal>}
 </>;
}
function FabricForm({onClose}){const {data,branch,mutate,notify}=useApp(),[form,setForm]=useState({name:'',category:'Wax',color:'',quantity:'',unit_cost:'',threshold:'3',supplier_id:''}),[busy,setBusy]=useState(false),change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);const id=uuid(),body={...form,id,branch_id:branch==='all'?data.branches[0]?.id:branch,quantity:Number(form.quantity)||0,unit_cost:Number(form.unit_cost)||0,threshold:Number(form.threshold)||3,supplier_id:form.supplier_id||null};try{await mutate('POST','/api/fabrics',body,old=>({...old,fabrics:[{...body,unit:'m',created_at:new Date().toISOString()},...old.fabrics]}));notify('Tissu ajouté au stock.');onClose();}catch(e){notify(e.message,'error')}finally{setBusy(false)}};return <Modal title="Ajouter un tissu" subtitle="Un stock précis, sans prise de tête." onClose={onClose}><form className="form-stack" onSubmit={submit}><Input label="Nom du tissu" name="name" value={form.name} onChange={change} placeholder="Ex. Wax fleurs de nuit" required/><div className="form-two"><Select label="Catégorie" name="category" value={form.category} onChange={change}>{['Wax','Bazin','Satin','Lin','Dentelle','Coton','Autre'].map(x=><option key={x}>{x}</option>)}</Select><Input label="Couleur" name="color" value={form.color} onChange={change} placeholder="Ex. Indigo"/></div><div className="form-two"><Input label="Quantité disponible (m)" name="quantity" type="number" step="0.1" min="0" value={form.quantity} onChange={change} placeholder="Ex. 12"/><Input label="Coût par mètre (FCFA)" name="unit_cost" type="number" min="0" value={form.unit_cost} onChange={change} placeholder="Ex. 4500"/></div><div className="form-two"><Input label="Alerte à partir de (m)" name="threshold" type="number" step="0.1" min="0" value={form.threshold} onChange={change}/><Select label="Fournisseur" name="supplier_id" value={form.supplier_id} onChange={change}><option value="">Pas de fournisseur</option>{data.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</Select></div><FormActions onCancel={onClose} loading={busy} label="Ajouter au stock"/></form></Modal>}
function SupplierForm({onClose}){const {mutate,notify}=useApp(),[form,setForm]=useState({name:'',phone:'',city:'',notes:''}),[busy,setBusy]=useState(false),change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);const id=uuid(),body={...form,id};try{await mutate('POST','/api/suppliers',body,old=>({...old,suppliers:[{...body,created_at:new Date().toISOString()},...old.suppliers]}));notify('Fournisseur ajouté.');onClose();}catch(e){notify(e.message,'error')}finally{setBusy(false)}};return <Modal title="Nouveau fournisseur" subtitle="Gardez les bons contacts à portée de main." onClose={onClose}><form className="form-stack" onSubmit={submit}><Input label="Nom du fournisseur" name="name" value={form.name} onChange={change} required placeholder="Ex. Maison du Tissu"/><Input label="Téléphone" name="phone" type="tel" value={form.phone} onChange={change} placeholder="+225 ..."/><Input label="Ville ou marché" name="city" value={form.city} onChange={change} placeholder="Ex. Adjamé, Abidjan"/><Input label="Notes utiles" name="notes" as="textarea" rows={2} value={form.notes} onChange={change}/><FormActions onCancel={onClose} loading={busy} label="Ajouter le fournisseur"/></form></Modal>}
function PurchaseForm({fabric,onClose}){const {data,mutate,notify}=useApp(),[form,setForm]=useState({quantity:'',amount:'',supplier_id:fabric.supplier_id||''}),[busy,setBusy]=useState(false),change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);const id=uuid(),body={...form,id,fabric_id:fabric.id,quantity:Number(form.quantity),amount:Number(form.amount),supplier_id:form.supplier_id||null};try{await mutate('POST','/api/purchases',body,old=>({...old,fabrics:old.fabrics.map(f=>f.id===fabric.id?{...f,quantity:f.quantity+Number(form.quantity)}:f),expenses:[{...body,category:'Achat tissu',label:'Achat : '+fabric.name,branch_id:fabric.branch_id,created_at:new Date().toISOString()},...old.expenses]}));notify('Achat enregistré. Le stock a été mis à jour.');onClose();}catch(e){notify(e.message,'error')}finally{setBusy(false)}};return <Modal title="Réapprovisionner le stock" subtitle={fabric.name+' · '+fabric.quantity+' m disponibles'} onClose={onClose}><form className="form-stack" onSubmit={submit}><div className="form-two"><Input label="Quantité achetée (m)" type="number" step="0.1" min="0.1" name="quantity" value={form.quantity} onChange={change} required placeholder="Ex. 10"/><Input label="Montant total (FCFA)" name="amount" type="number" min="0" value={form.amount} onChange={change} required placeholder="Ex. 45000"/></div><Select label="Fournisseur" name="supplier_id" value={form.supplier_id} onChange={change}><option value="">Non précisé</option>{data.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</Select><div className="form-info"><Info size={16}/> Cet achat augmentera le stock et apparaîtra dans les dépenses de la caisse.</div><FormActions onCancel={onClose} loading={busy} label="Enregistrer l’achat"/></form></Modal>}
