import React,{useState} from 'react';
import {Plus, UsersRound, Building2, Scissors, Wallet, GraduationCap, Crown, ChevronRight, MapPin, Phone, ShoppingBag, ArrowRight, Info, UserPlus, Store, Layers3, TrendingUp, LockKeyhole} from 'lucide-react';
import {useApp} from '../App.jsx';
import {PageHeader,Card,PanelHead,Button,Badge,Avatar,Tabs,Modal,Input,Select,FormActions,Empty,StatCard} from '../components.jsx';
import {money,fmt,uuid} from '../utils.js';
const labels={owner:'Propriétaire',tailor:'Couturier',apprentice:'Apprenti',accountant:'Comptable'},icons={owner:Crown,tailor:Scissors,apprentice:GraduationCap,accountant:Wallet};
export default function Team(){const {data,branch,setBranch}=useApp(),[tab,setTab]=useState('team'),[newMember,setNewMember]=useState(false),[newBranch,setNewBranch]=useState(false),[resetMember,setResetMember]=useState(null),members=data.team.filter(x=>branch==='all'||x.branch_id===branch),branches=data.branches;
 return <><PageHeader eyebrow="ENSEMBLE, PLUS LOIN" title="Équipe & succursales" subtitle="Les bonnes personnes, au bon endroit, sur les bonnes créations." action={data.user.role==='owner'&&<Button icon={Plus} onClick={()=>tab==='team'?setNewMember(true):setNewBranch(true)}>{tab==='team'?'Ajouter un membre':'Ajouter une succursale'}</Button>}/>
 <div className="team-summary-grid"><Card className="team-summary"><span><UsersRound size={20}/></span><strong>{members.length}</strong><small>Membres de l’équipe</small></Card><Card className="team-summary"><span><Building2 size={20}/></span><strong>{branches.length}</strong><small>Succursale{branches.length>1?'s':''} active{branches.length>1?'s':''}</small></Card><Card className="team-summary"><span><ShoppingBag size={20}/></span><strong>{data.orders.filter(o=>o.status==='active'&&(branch==='all'||o.branch_id===branch)).length}</strong><small>Travaux en cours</small></Card><Card className="team-summary"><span><Wallet size={20}/></span><strong>{money(data.orders.filter(o=>o.status==='active'&&(branch==='all'||o.branch_id===branch)).reduce((a,o)=>a+(o.commission||0),0))}</strong><small>Commissions prévues</small></Card></div>
 <div className="production-topline"><Tabs items={[{key:'team',label:'Membres',count:members.length},{key:'branches',label:'Succursales',count:branches.length}]} active={tab} onChange={setTab}/></div>
 {tab==='team'&&<div className="team-layout"><div className="team-card-grid">{members.map((member,i)=>{const workload=data.orders.filter(o=>o.assigned_user_id===member.id&&o.status==='active'),commission=data.orders.filter(o=>o.assigned_user_id===member.id).reduce((sum,o)=>sum+(o.commission||0),0),Icon=icons[member.role]||Scissors;return <Card className="member-card" key={member.id}><div className="member-card-top"><Avatar name={member.name} size="lg" color={i}/><Badge tone={member.role==='owner'?'amber':member.role==='tailor'?'mint':'gray'}><Icon size={13}/>{labels[member.role]}</Badge></div><h3>{member.name}</h3><p>{member.phone||member.email||'—'}</p><div className="member-divider"/><div className="member-metrics"><div><small>COMMANDES EN COURS</small><strong>{workload.length}</strong></div><div><small>COMMISSIONS ESTIMÉES</small><strong>{money(commission)}</strong></div></div><div className="member-workload"><span>Charge actuelle</span><div className="member-track"><span style={{width:Math.min(100,workload.length*20)+'%'}}/></div></div><small className="member-branch"><MapPin size={13}/>{branches.find(b=>b.id===member.branch_id)?.name||'Succursale'}</small>{data.user.role==='owner'&&member.role!=='owner'&&<button className="member-reset-link" onClick={()=>setResetMember(member)}><LockKeyhole size={14}/> Modifier son mot de passe</button>}</Card>})}{data.user.role==='owner'&&<button className="fabric-add-card member-add" onClick={()=>setNewMember(true)}><span><UserPlus size={24}/></span><strong>Inviter un membre</strong><small>Grandissez ensemble, simplement.</small></button>}</div><Card className="role-guide"><h3>Chacun son rôle</h3><p>Des accès adaptés pour que toute l’équipe avance sans se gêner.</p>{[['Propriétaire','Gère tout l’atelier'],['Couturier','Suit les clients et la production'],['Apprenti','Fait avancer les étapes'],['Comptable','Suit la caisse et les encaissements']].map(([title,sub],i)=><div key={title}><span className={'role-guide-icon role-'+i}>{React.createElement([Crown,Scissors,GraduationCap,Wallet][i],{size:17})}</span><span><strong>{title}</strong><small>{sub}</small></span></div>)}</Card></div>}
 {tab==='branches'&&<div className="branches-grid">{branches.map(b=>{const os=data.orders.filter(o=>o.branch_id===b.id),active=os.filter(o=>o.status==='active');return <Card className="branch-card" key={b.id}><div className="branch-card-heading"><span className="branch-icon"><Building2 size={23}/></span>{b.is_primary?<Badge tone="mint">Atelier principal</Badge>:<Badge tone="blue">Succursale</Badge>}</div><h3>{b.name}</h3><p><MapPin size={16}/>{[b.address,b.city].filter(Boolean).join(', ')||'Adresse à ajouter'}</p><div className="branch-metrics"><div><strong>{active.length}</strong><small>commandes en cours</small></div><div><strong>{data.team.filter(u=>u.branch_id===b.id).length}</strong><small>membres</small></div></div><button onClick={()=>setBranch(b.id)}>Afficher cette succursale <ArrowRight size={15}/></button></Card>})}{data.user.role==='owner'&&<button className="fabric-add-card" onClick={()=>setNewBranch(true)}><span><Plus size={24}/></span><strong>Nouvelle succursale</strong><small>Développez votre enseigne au même endroit.</small></button>}</div>}
 {newMember&&<MemberForm onClose={()=>setNewMember(false)}/>} {newBranch&&<BranchForm onClose={()=>setNewBranch(false)}/>} {resetMember&&<ResetMemberPassword member={resetMember} onClose={()=>setResetMember(null)}/>}
 </>;
}
function MemberForm({onClose}){
 const {data,branch,request,refresh,notify}=useApp(),[form,setForm]=useState({name:'',identifier:'',password:'',role:'tailor',branch_id:branch==='all'?data.branches[0]?.id:branch}),[busy,setBusy]=useState(false);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();setBusy(true);try{await request('/api/team',{method:'POST',body:form});await refresh();notify('Membre ajouté. Transmettez-lui son identifiant et son mot de passe en privé.');onClose();}catch(err){notify(err.message,'error');}finally{setBusy(false);}};
 return <Modal title="Ajouter un membre" subtitle="Choisissez ses accès avant de l’ajouter à l’équipe." onClose={onClose}>
  <form className="form-stack" onSubmit={submit}>
   <Input label="Nom complet" name="name" value={form.name} onChange={change} required placeholder="Ex. Clarisse Yao"/>
   <Input label="E-mail ou numéro de téléphone" name="identifier" value={form.identifier} onChange={change} required placeholder="clarisse@atelier.ci ou +225 ..."/>
   <Input label="Mot de passe initial" name="password" type="password" autoComplete="new-password" minLength={10} maxLength={72} value={form.password} onChange={change} required hint="Au moins 10 caractères. Le membre pourra le changer dans Paramètres."/>
   <Select label="Rôle" name="role" value={form.role} onChange={change}><option value="tailor">Couturier / couturière</option><option value="apprentice">Apprenti / apprentie</option><option value="accountant">Comptable</option></Select>
   <Select label="Succursale" name="branch_id" value={form.branch_id} onChange={change}>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select>
   <div className="form-info"><Info size={16}/> Transmettez le mot de passe en privé. Il ne sera plus affiché après la création.</div>
   <FormActions onCancel={onClose} loading={busy} label="Ajouter à l’équipe"/>
  </form>
 </Modal>;
}
function ResetMemberPassword({member,onClose}){
 const {request,notify}=useApp(),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);try{await request('/api/team/'+member.id+'/password',{method:'PATCH',body:{password}});notify('Mot de passe mis à jour. Ses autres sessions sont déconnectées.');onClose();}catch(err){notify(err.message,'error');}finally{setBusy(false);}};
 return <Modal title="Modifier son mot de passe" subtitle={member.name} onClose={onClose}><form className="form-stack" onSubmit={submit}>
  <Input label="Nouveau mot de passe" type="password" autoComplete="new-password" minLength={10} maxLength={72} value={password} onChange={e=>setPassword(e.target.value)} required hint="Au moins 10 caractères."/>
  <div className="form-info"><Info size={16}/> Transmettez ce nouveau mot de passe au membre en privé. Ses anciennes sessions seront invalidées.</div>
  <FormActions onCancel={onClose} loading={busy} label="Changer le mot de passe"/>
 </form></Modal>;
}
function BranchForm({onClose}){const {mutate,notify}=useApp(),[form,setForm]=useState({name:'',address:'',city:'',phone:''}),[busy,setBusy]=useState(false),change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);const id=uuid(),body={...form,id};try{await mutate('POST','/api/branches',body,old=>({...old,branches:[...old.branches,{...body,created_at:new Date().toISOString()}]}));notify('Nouvelle succursale ajoutée.');onClose();}catch(e){notify(e.message,'error')}finally{setBusy(false)}};return <Modal title="Nouvelle succursale" subtitle="La même enseigne, un nouvel atelier." onClose={onClose}><form className="form-stack" onSubmit={submit}><Input label="Nom de la succursale" name="name" value={form.name} onChange={change} required placeholder="Ex. Marcory — Succursale 2"/><Input label="Adresse" name="address" value={form.address} onChange={change} placeholder="Rue, quartier..."/><Input label="Ville" name="city" value={form.city} onChange={change} required placeholder="Abidjan"/><Input label="Téléphone" type="tel" name="phone" value={form.phone} onChange={change} placeholder="+225 ..."/><FormActions onCancel={onClose} loading={busy} label="Créer la succursale"/></form></Modal>}
