import React, {useEffect,useState} from 'react';
import {X, Search, LoaderCircle, ArrowRight, Plus, ChevronRight, CircleCheck, AlertCircle, Inbox, ExternalLink} from 'lucide-react';
export function Button({children,variant='primary',size='',icon:Icon,loading=false,className='',...props}){return <button {...props} disabled={loading||props.disabled} className={`btn btn-${variant} ${size?'btn-'+size:''} ${className}`}>{loading?<LoaderCircle size={17} className="spin"/>:Icon&&<Icon size={17} strokeWidth={2}/>}<span>{children}</span></button>}
export function IconButton({icon:Icon,label,className='',...props}){return <button title={label} aria-label={label} className={'icon-button '+className} {...props}><Icon size={19}/></button>}
export function Badge({children,tone='gray',dot=false,className=''}){return <span className={`badge badge-${tone} ${className}`}>{dot&&<i className="badge-dot"/>}{children}</span>}
export function Avatar({name,size='md',color=0}){return <span className={`avatar avatar-${size} avatar-color-${color%5}`}>{String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}</span>}
export function Card({children,className='',...props}){return <div className={'card '+className} {...props}>{children}</div>}
export function PageHeader({eyebrow,title,subtitle,action,extra}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="page-header-actions">{extra}{action}</div></div>}
export function PanelHead({title,subtitle,action,icon:Icon}){return <div className="panel-head"><div className="panel-title-wrap">{Icon&&<div className="panel-icon"><Icon size={18}/></div>}<div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{action}</div>}
export function Modal({title,subtitle,children,onClose,wide=false,foot=null}){
 useEffect(()=>{const handler=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',handler);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow='';};},[onClose]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className={'modal-card '+(wide?'modal-wide':'')} role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><IconButton icon={X} label="Fermer" onClick={onClose}/></div><div className="modal-body">{children}</div>{foot&&<div className="modal-foot">{foot}</div>}</div></div>;
}
export function Field({label,children,hint,required=false,className=''}){return <label className={'form-field '+className}><span className="field-label">{label}{required&&<em> *</em>}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Input({label,hint,required,as='input',className='',...props}){let Tag=as;return <Field label={label} hint={hint} required={required} className={className}><Tag className="input" required={required} {...props}/></Field>}
export function Select({label,children,hint,required,...props}){return <Field label={label} hint={hint} required={required}><select className="input" required={required} {...props}>{children}</select></Field>}
export function Empty({icon:Icon=Inbox,title,description,action}){return <div className="empty-state"><div className="empty-icon"><Icon size={25}/></div><h3>{title}</h3><p>{description}</p>{action}</div>}
export function SearchInput({value,onChange,placeholder='Rechercher...',className=''}){return <div className={'search-input '+className}><Search size={17}/><input aria-label="Rechercher" placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Effacer" onClick={()=>onChange('')}><X size={15}/></button>}</div>}
export function SectionLink({children,onClick}){return <button className="section-link" onClick={onClick}>{children}<ArrowRight size={16}/></button>}
export function FormActions({onCancel,loading,label='Enregistrer'}){return <div className="form-actions"><Button type="button" variant="soft" onClick={onCancel}>Annuler</Button><Button type="submit" loading={loading}>{label}</Button></div>}
export function Toasts({toasts,remove}){return <div className="toast-region" aria-live="polite">{toasts.map(t=><div key={t.id} className={'toast toast-'+t.type}>{t.type==='error'?<AlertCircle size={18}/>:<CircleCheck size={18}/>}<span>{t.message}</span><button onClick={()=>remove(t.id)} aria-label="Fermer"><X size={15}/></button></div>)}</div>}
export function StatCard({label,value,sub,icon:Icon,tone='green',trend,onClick}){return <Card className={'stat-card '+(onClick?'stat-click':'')} onClick={onClick}><div className="stat-top"><span>{label}</span><span className={'stat-icon stat-icon-'+tone}><Icon size={20} strokeWidth={1.9}/></span></div><div className="stat-value">{value}</div><div className="stat-bottom">{trend&&<span className="stat-trend">{trend}</span>}<span>{sub}</span></div></Card>}
export function Tabs({items,active,onChange}){return <div className="tabs">{items.map(x=><button key={x.key} className={'tab '+(active===x.key?'active':'')} onClick={()=>onChange(x.key)}>{x.label}{x.count!=null&&<span>{x.count}</span>}</button>)}</div>}
export function Loading(){return <div className="loading-state"><div className="loading-mark">K<span>✦</span></div><LoaderCircle size={23} className="spin"/><span>On prépare votre atelier...</span></div>}
export function SmallSpinner(){return <LoaderCircle size={17} className="spin"/>}
export function External({href,children,...props}){return <a href={href} target="_blank" rel="noopener noreferrer" {...props}>{children}<ExternalLink size={14}/></a>}
